
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May 19 2026 11:34:54 IST (May 19 2026 06:04:54 UTC)

// Verification Directory fv/fifo_sync 

module fifo_sync(clk, rst_n, cs, wr_en, rd_en, data_in, data_out,
     empty, full, SE, scan_in, scan_out);
  input clk, rst_n, cs, wr_en, rd_en, SE, scan_in;
  input [31:0] data_in;
  output [31:0] data_out;
  output empty, full, scan_out;
  wire clk, rst_n, cs, wr_en, rd_en, SE, scan_in;
  wire [31:0] data_in;
  wire [31:0] data_out;
  wire empty, full, scan_out;
  wire [31:0] \fifo[2] ;
  wire [31:0] \fifo[5] ;
  wire [31:0] \fifo[4] ;
  wire [31:0] \fifo[3] ;
  wire [31:0] \fifo[7] ;
  wire [31:0] \fifo[1] ;
  wire [3:0] write_pointer;
  wire [3:0] read_pointer;
  wire [31:0] \fifo[0] ;
  wire [31:0] \fifo[6] ;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_37, n_38, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_137, n_138, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_211, n_212, n_213, n_214;
  wire n_215, n_216, n_217, n_218, n_219, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_237, n_238;
  wire n_239, n_240, n_241, n_242, n_243, n_244, n_245, n_246;
  wire n_247, n_248, n_249, n_250, n_251, n_252, n_253, n_254;
  wire n_255, n_256, n_257, n_258, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_265, n_266, n_267, n_268, n_269, n_270;
  wire n_271, n_272, n_273, n_274, n_275, n_276, n_277, n_278;
  wire n_279, n_280, n_281, n_282, n_283, n_284, n_285, n_286;
  wire n_287, n_309, n_311;
  SDFFQX1 \data_out_reg[0] (.CK (clk), .D (n_264), .SI (scan_in), .SE
       (SE), .Q (data_out[0]));
  SDFFQX1 \data_out_reg[4] (.CK (clk), .D (n_269), .SI (data_out[3]),
       .SE (SE), .Q (data_out[4]));
  SDFFQX1 \data_out_reg[14] (.CK (clk), .D (n_274), .SI (data_out[13]),
       .SE (SE), .Q (data_out[14]));
  SDFFQX1 \data_out_reg[15] (.CK (clk), .D (n_278), .SI (data_out[14]),
       .SE (SE), .Q (data_out[15]));
  SDFFQX1 \data_out_reg[16] (.CK (clk), .D (n_283), .SI (data_out[15]),
       .SE (SE), .Q (data_out[16]));
  SDFFQX1 \data_out_reg[5] (.CK (clk), .D (n_259), .SI (data_out[4]),
       .SE (SE), .Q (data_out[5]));
  SDFFQX1 \data_out_reg[17] (.CK (clk), .D (n_280), .SI (data_out[16]),
       .SE (SE), .Q (data_out[17]));
  SDFFQX1 \data_out_reg[6] (.CK (clk), .D (n_287), .SI (data_out[5]),
       .SE (SE), .Q (data_out[6]));
  SDFFQX1 \data_out_reg[18] (.CK (clk), .D (n_266), .SI (data_out[17]),
       .SE (SE), .Q (data_out[18]));
  SDFFQX1 \data_out_reg[7] (.CK (clk), .D (n_270), .SI (data_out[6]),
       .SE (SE), .Q (data_out[7]));
  SDFFQX1 \data_out_reg[19] (.CK (clk), .D (n_267), .SI (data_out[18]),
       .SE (SE), .Q (data_out[19]));
  SDFFQX1 \data_out_reg[20] (.CK (clk), .D (n_263), .SI (data_out[19]),
       .SE (SE), .Q (data_out[20]));
  SDFFQX1 \data_out_reg[21] (.CK (clk), .D (n_262), .SI (data_out[20]),
       .SE (SE), .Q (data_out[21]));
  SDFFQX1 \data_out_reg[22] (.CK (clk), .D (n_261), .SI (data_out[21]),
       .SE (SE), .Q (data_out[22]));
  SDFFQX1 \data_out_reg[11] (.CK (clk), .D (n_279), .SI (data_out[10]),
       .SE (SE), .Q (data_out[11]));
  SDFFQX1 \data_out_reg[2] (.CK (clk), .D (n_265), .SI (data_out[1]),
       .SE (SE), .Q (data_out[2]));
  SDFFQX1 \data_out_reg[9] (.CK (clk), .D (n_281), .SI (data_out[8]),
       .SE (SE), .Q (data_out[9]));
  SDFFQX1 \data_out_reg[24] (.CK (clk), .D (n_286), .SI (data_out[23]),
       .SE (SE), .Q (data_out[24]));
  SDFFQX1 \data_out_reg[25] (.CK (clk), .D (n_282), .SI (data_out[24]),
       .SE (SE), .Q (data_out[25]));
  SDFFQX1 \data_out_reg[10] (.CK (clk), .D (n_284), .SI (data_out[9]),
       .SE (SE), .Q (data_out[10]));
  SDFFQX1 \data_out_reg[27] (.CK (clk), .D (n_277), .SI (data_out[26]),
       .SE (SE), .Q (data_out[27]));
  SDFFQX1 \data_out_reg[31] (.CK (clk), .D (n_268), .SI (data_out[30]),
       .SE (SE), .Q (data_out[31]));
  SDFFQX1 \data_out_reg[28] (.CK (clk), .D (n_276), .SI (data_out[27]),
       .SE (SE), .Q (data_out[28]));
  SDFFQX1 \data_out_reg[3] (.CK (clk), .D (n_285), .SI (data_out[2]),
       .SE (SE), .Q (data_out[3]));
  SDFFQX1 \data_out_reg[12] (.CK (clk), .D (n_275), .SI (data_out[11]),
       .SE (SE), .Q (data_out[12]));
  SDFFQX1 \data_out_reg[29] (.CK (clk), .D (n_272), .SI (data_out[28]),
       .SE (SE), .Q (data_out[29]));
  SDFFQX1 \data_out_reg[30] (.CK (clk), .D (n_271), .SI (data_out[29]),
       .SE (SE), .Q (data_out[30]));
  SDFFQX1 \data_out_reg[13] (.CK (clk), .D (n_273), .SI (data_out[12]),
       .SE (SE), .Q (data_out[13]));
  SDFFQX1 \data_out_reg[23] (.CK (clk), .D (n_260), .SI (data_out[22]),
       .SE (SE), .Q (data_out[23]));
  SDFFQX1 \data_out_reg[1] (.CK (clk), .D (n_256), .SI (data_out[0]),
       .SE (SE), .Q (data_out[1]));
  SDFFQX1 \data_out_reg[8] (.CK (clk), .D (n_257), .SI (data_out[7]),
       .SE (SE), .Q (data_out[8]));
  SDFFQX1 \data_out_reg[26] (.CK (clk), .D (n_258), .SI (data_out[25]),
       .SE (SE), .Q (data_out[26]));
  NAND2XL g7631__2398(.A (n_128), .B (n_244), .Y (n_287));
  NAND2XL g7644__5107(.A (n_104), .B (n_253), .Y (n_286));
  NAND2XL g7645__6260(.A (n_95), .B (n_243), .Y (n_285));
  NAND2XL g7646__4319(.A (n_100), .B (n_250), .Y (n_284));
  NAND2XL g7629__8428(.A (n_131), .B (n_255), .Y (n_283));
  NAND2XL g7647__5526(.A (n_101), .B (n_224), .Y (n_282));
  NAND2XL g7627__6783(.A (n_106), .B (n_239), .Y (n_281));
  NAND2XL g7630__3680(.A (n_127), .B (n_232), .Y (n_280));
  NAND2XL g7649__1617(.A (n_96), .B (n_234), .Y (n_279));
  NAND2XL g7628__2802(.A (n_121), .B (n_231), .Y (n_278));
  NAND2XL g7650__1705(.A (n_85), .B (n_228), .Y (n_277));
  NAND2XL g7651__5122(.A (n_120), .B (n_249), .Y (n_276));
  NAND2XL g7652__8246(.A (n_91), .B (n_236), .Y (n_275));
  NAND2XL g7643__7098(.A (n_114), .B (n_233), .Y (n_274));
  NAND2XL g7657__6131(.A (n_88), .B (n_223), .Y (n_273));
  NAND2XL g7653__1881(.A (n_144), .B (n_237), .Y (n_272));
  NAND2XL g7654__5115(.A (n_90), .B (n_225), .Y (n_271));
  NAND2XL g7633__7482(.A (n_122), .B (n_230), .Y (n_270));
  NAND2XL g7655__4733(.A (n_78), .B (n_227), .Y (n_269));
  NAND2XL g7656__6161(.A (n_137), .B (n_221), .Y (n_268));
  NAND2XL g7634__9315(.A (n_123), .B (n_235), .Y (n_267));
  NAND2XL g7632__9945(.A (n_126), .B (n_226), .Y (n_266));
  NAND2XL g7658__2883(.A (n_93), .B (n_229), .Y (n_265));
  NAND2XL g7635__2346(.A (n_75), .B (n_238), .Y (n_264));
  NAND2XL g7636__1666(.A (n_118), .B (n_222), .Y (n_263));
  NAND2XL g7638__7410(.A (n_71), .B (n_246), .Y (n_262));
  NAND2XL g7640__6417(.A (n_109), .B (n_241), .Y (n_261));
  NAND2XL g7641__5477(.A (n_107), .B (n_254), .Y (n_260));
  NAND2XL g7642__2398(.A (n_76), .B (n_248), .Y (n_259));
  NAND2XL g7648__5107(.A (n_99), .B (n_220), .Y (n_258));
  NAND2XL g7637__6260(.A (n_87), .B (n_218), .Y (n_257));
  NAND2XL g7639__4319(.A (n_119), .B (n_219), .Y (n_256));
  AOI221XL g7674__8428(.A0 (n_240), .A1 (\fifo[2] [16]), .B0 (n_251),
       .B1 (\fifo[5] [16]), .C0 (n_191), .Y (n_255));
  AOI221XL g7667__5526(.A0 (n_242), .A1 (\fifo[4] [23]), .B0 (n_252),
       .B1 (\fifo[3] [23]), .C0 (n_209), .Y (n_254));
  AOI221XL g7668__6783(.A0 (n_252), .A1 (\fifo[3] [24]), .B0 (n_251),
       .B1 (\fifo[5] [24]), .C0 (n_206), .Y (n_253));
  AOI221XL g7669__3680(.A0 (n_252), .A1 (\fifo[3] [10]), .B0 (n_251),
       .B1 (\fifo[5] [10]), .C0 (n_202), .Y (n_250));
  AOI221X1 g7670__1617(.A0 (n_252), .A1 (\fifo[3] [28]), .B0 (n_247),
       .B1 (\fifo[7] [28]), .C0 (n_201), .Y (n_249));
  AOI221XL g7671__2802(.A0 (n_245), .A1 (\fifo[1] [5]), .B0 (n_247),
       .B1 (\fifo[7] [5]), .C0 (n_190), .Y (n_248));
  AOI221XL g7672__1705(.A0 (n_245), .A1 (\fifo[1] [21]), .B0 (n_247),
       .B1 (\fifo[7] [21]), .C0 (n_187), .Y (n_246));
  AOI221X1 g7666__5122(.A0 (n_252), .A1 (\fifo[3] [6]), .B0 (n_247),
       .B1 (\fifo[7] [6]), .C0 (n_217), .Y (n_244));
  AOI221XL g7675__8246(.A0 (n_242), .A1 (\fifo[4] [3]), .B0 (n_251),
       .B1 (\fifo[5] [3]), .C0 (n_211), .Y (n_243));
  AOI221XL g7676__7098(.A0 (n_240), .A1 (\fifo[2] [22]), .B0 (n_247),
       .B1 (\fifo[7] [22]), .C0 (n_212), .Y (n_241));
  AOI221XL g7677__6131(.A0 (n_252), .A1 (\fifo[3] [9]), .B0 (n_247),
       .B1 (\fifo[7] [9]), .C0 (n_208), .Y (n_239));
  AOI221XL g7678__1881(.A0 (n_245), .A1 (\fifo[1] [0]), .B0 (n_247),
       .B1 (\fifo[7] [0]), .C0 (n_188), .Y (n_238));
  AOI221XL g7679__5115(.A0 (n_240), .A1 (\fifo[2] [29]), .B0 (n_247),
       .B1 (\fifo[7] [29]), .C0 (n_203), .Y (n_237));
  AOI221XL g7680__7482(.A0 (n_240), .A1 (\fifo[2] [12]), .B0 (n_247),
       .B1 (\fifo[7] [12]), .C0 (n_207), .Y (n_236));
  AOI221XL g7659__4733(.A0 (n_252), .A1 (\fifo[3] [19]), .B0 (n_247),
       .B1 (\fifo[7] [19]), .C0 (n_183), .Y (n_235));
  AOI221XL g7686__6161(.A0 (n_252), .A1 (\fifo[3] [11]), .B0 (n_251),
       .B1 (\fifo[5] [11]), .C0 (n_199), .Y (n_234));
  AOI221XL g7682__9315(.A0 (n_245), .A1 (\fifo[1] [14]), .B0 (n_247),
       .B1 (\fifo[7] [14]), .C0 (n_216), .Y (n_233));
  AOI221XL g7660__9945(.A0 (n_240), .A1 (\fifo[2] [17]), .B0 (n_247),
       .B1 (\fifo[7] [17]), .C0 (n_192), .Y (n_232));
  AOI221XL g7683__2883(.A0 (n_242), .A1 (\fifo[4] [15]), .B0 (n_251),
       .B1 (\fifo[5] [15]), .C0 (n_189), .Y (n_231));
  AOI221XL g7661__2346(.A0 (n_245), .A1 (\fifo[1] [7]), .B0 (n_240),
       .B1 (\fifo[2] [7]), .C0 (n_186), .Y (n_230));
  AOI221XL g7684__1666(.A0 (n_242), .A1 (\fifo[4] [2]), .B0 (n_251),
       .B1 (\fifo[5] [2]), .C0 (n_205), .Y (n_229));
  AOI221XL g7685__7410(.A0 (n_245), .A1 (\fifo[1] [27]), .B0 (n_251),
       .B1 (\fifo[5] [27]), .C0 (n_200), .Y (n_228));
  AOI221XL g7681__6417(.A0 (n_247), .A1 (\fifo[7] [4]), .B0 (n_245),
       .B1 (\fifo[1] [4]), .C0 (n_215), .Y (n_227));
  AOI221XL g7687__5477(.A0 (n_242), .A1 (\fifo[4] [18]), .B0 (n_247),
       .B1 (\fifo[7] [18]), .C0 (n_185), .Y (n_226));
  AOI221XL g7663__2398(.A0 (n_240), .A1 (\fifo[2] [30]), .B0 (n_251),
       .B1 (\fifo[5] [30]), .C0 (n_210), .Y (n_225));
  AOI221XL g7689__5107(.A0 (n_242), .A1 (\fifo[4] [25]), .B0 (n_251),
       .B1 (\fifo[5] [25]), .C0 (n_204), .Y (n_224));
  AOI221XL g7665__6260(.A0 (n_240), .A1 (\fifo[2] [13]), .B0 (n_247),
       .B1 (\fifo[7] [13]), .C0 (n_214), .Y (n_223));
  AOI221XL g7690__4319(.A0 (n_251), .A1 (\fifo[5] [20]), .B0 (n_247),
       .B1 (\fifo[7] [20]), .C0 (n_184), .Y (n_222));
  AOI221XL g7664__8428(.A0 (n_240), .A1 (\fifo[2] [31]), .B0 (n_247),
       .B1 (\fifo[7] [31]), .C0 (n_213), .Y (n_221));
  SDFFRHQX1 \write_pointer_reg[2] (.RN (rst_n), .CK (clk), .D (n_180),
       .SI (write_pointer[1]), .SE (SE), .Q (write_pointer[2]));
  AOI221XL g7673__5526(.A0 (n_245), .A1 (\fifo[1] [26]), .B0 (n_240),
       .B1 (\fifo[2] [26]), .C0 (n_181), .Y (n_220));
  AOI221XL g7662__6783(.A0 (n_240), .A1 (\fifo[2] [1]), .B0 (n_247),
       .B1 (\fifo[7] [1]), .C0 (n_177), .Y (n_219));
  AOI221XL g7688__3680(.A0 (n_245), .A1 (\fifo[1] [8]), .B0 (n_242),
       .B1 (\fifo[4] [8]), .C0 (n_182), .Y (n_218));
  SDFFRHQX1 \write_pointer_reg[0] (.RN (rst_n), .CK (clk), .D (n_136),
       .SI (read_pointer[3]), .SE (SE), .Q (write_pointer[0]));
  NAND2XL g7702__1617(.A (n_125), .B (n_165), .Y (n_217));
  NAND2XL g7730__2802(.A (n_116), .B (n_175), .Y (n_216));
  NAND2XL g7729__1705(.A (n_86), .B (n_145), .Y (n_215));
  NAND2XL g7728__5122(.A (n_67), .B (n_146), .Y (n_214));
  NAND2XL g7727__8246(.A (n_147), .B (n_92), .Y (n_213));
  NAND2XL g7711__7098(.A (n_108), .B (n_176), .Y (n_212));
  NAND2XL g7726__6131(.A (n_113), .B (n_150), .Y (n_211));
  NAND2XL g7725__1881(.A (n_149), .B (n_89), .Y (n_210));
  NAND2XL g7713__5115(.A (n_70), .B (n_152), .Y (n_209));
  NAND2XL g7714__7482(.A (n_103), .B (n_158), .Y (n_208));
  NAND2XL g7724__4733(.A (n_115), .B (n_148), .Y (n_207));
  NAND2XL g7715__6161(.A (n_102), .B (n_157), .Y (n_206));
  NAND2XL g7716__9315(.A (n_69), .B (n_156), .Y (n_205));
  NAND2XL g7717__9945(.A (n_68), .B (n_160), .Y (n_204));
  NAND2XL g7723__2883(.A (n_139), .B (n_151), .Y (n_203));
  NAND2XL g7718__2346(.A (n_98), .B (n_155), .Y (n_202));
  NAND2XL g7722__1666(.A (n_143), .B (n_159), .Y (n_201));
  NAND2XL g7720__7410(.A (n_94), .B (n_154), .Y (n_200));
  NAND2XL g7721__6417(.A (n_105), .B (n_153), .Y (n_199));
  SMDFFHQX1 \fifo_reg[0][23] (.CK (clk), .D0 (data_in[23]), .D1
       (\fifo[0] [23]), .S0 (n_198), .SI (\fifo[0] [22]), .SE (SE), .Q
       (\fifo[0] [23]));
  SMDFFHQX1 \fifo_reg[0][30] (.CK (clk), .D0 (data_in[30]), .D1
       (\fifo[0] [30]), .S0 (n_198), .SI (\fifo[0] [29]), .SE (SE), .Q
       (\fifo[0] [30]));
  SMDFFHQX1 \fifo_reg[0][22] (.CK (clk), .D0 (data_in[22]), .D1
       (\fifo[0] [22]), .S0 (n_198), .SI (\fifo[0] [21]), .SE (SE), .Q
       (\fifo[0] [22]));
  SMDFFHQX1 \fifo_reg[0][2] (.CK (clk), .D0 (data_in[2]), .D1
       (\fifo[0] [2]), .S0 (n_198), .SI (\fifo[0] [1]), .SE (SE), .Q
       (\fifo[0] [2]));
  SMDFFHQX1 \fifo_reg[5][6] (.CK (clk), .D0 (\fifo[5] [6]), .D1
       (data_in[6]), .S0 (n_197), .SI (\fifo[5] [5]), .SE (SE), .Q
       (\fifo[5] [6]));
  SMDFFHQX1 \fifo_reg[0][18] (.CK (clk), .D0 (data_in[18]), .D1
       (\fifo[0] [18]), .S0 (n_198), .SI (\fifo[0] [17]), .SE (SE), .Q
       (\fifo[0] [18]));
  SMDFFHQX1 \fifo_reg[0][6] (.CK (clk), .D0 (data_in[6]), .D1
       (\fifo[0] [6]), .S0 (n_198), .SI (\fifo[0] [5]), .SE (SE), .Q
       (\fifo[0] [6]));
  SMDFFHQX1 \fifo_reg[5][10] (.CK (clk), .D0 (\fifo[5] [10]), .D1
       (data_in[10]), .S0 (n_197), .SI (\fifo[5] [9]), .SE (SE), .Q
       (\fifo[5] [10]));
  SMDFFHQX1 \fifo_reg[1][26] (.CK (clk), .D0 (data_in[26]), .D1
       (\fifo[1] [26]), .S0 (n_194), .SI (\fifo[1] [25]), .SE (SE), .Q
       (\fifo[1] [26]));
  SMDFFHQX1 \fifo_reg[6][2] (.CK (clk), .D0 (data_in[2]), .D1
       (\fifo[6] [2]), .S0 (n_193), .SI (\fifo[6] [1]), .SE (SE), .Q
       (\fifo[6] [2]));
  SMDFFHQX1 \fifo_reg[4][22] (.CK (clk), .D0 (data_in[22]), .D1
       (\fifo[4] [22]), .S0 (n_196), .SI (\fifo[4] [21]), .SE (SE), .Q
       (\fifo[4] [22]));
  SMDFFHQX1 \fifo_reg[4][26] (.CK (clk), .D0 (data_in[26]), .D1
       (\fifo[4] [26]), .S0 (n_196), .SI (\fifo[4] [25]), .SE (SE), .Q
       (\fifo[4] [26]));
  SMDFFHQX1 \fifo_reg[2][22] (.CK (clk), .D0 (data_in[22]), .D1
       (\fifo[2] [22]), .S0 (n_195), .SI (\fifo[2] [21]), .SE (SE), .Q
       (\fifo[2] [22]));
  SMDFFHQX1 \fifo_reg[2][26] (.CK (clk), .D0 (data_in[26]), .D1
       (\fifo[2] [26]), .S0 (n_195), .SI (\fifo[2] [25]), .SE (SE), .Q
       (\fifo[2] [26]));
  SMDFFHQX1 \fifo_reg[1][20] (.CK (clk), .D0 (data_in[20]), .D1
       (\fifo[1] [20]), .S0 (n_194), .SI (\fifo[1] [19]), .SE (SE), .Q
       (\fifo[1] [20]));
  SMDFFHQX1 \fifo_reg[6][22] (.CK (clk), .D0 (data_in[22]), .D1
       (\fifo[6] [22]), .S0 (n_193), .SI (\fifo[6] [21]), .SE (SE), .Q
       (\fifo[6] [22]));
  SMDFFHQX1 \fifo_reg[6][26] (.CK (clk), .D0 (data_in[26]), .D1
       (\fifo[6] [26]), .S0 (n_193), .SI (\fifo[6] [25]), .SE (SE), .Q
       (\fifo[6] [26]));
  SMDFFHQX1 \fifo_reg[5][26] (.CK (clk), .D0 (\fifo[5] [26]), .D1
       (data_in[26]), .S0 (n_197), .SI (\fifo[5] [25]), .SE (SE), .Q
       (\fifo[5] [26]));
  SMDFFHQX1 \fifo_reg[1][18] (.CK (clk), .D0 (data_in[18]), .D1
       (\fifo[1] [18]), .S0 (n_194), .SI (\fifo[1] [17]), .SE (SE), .Q
       (\fifo[1] [18]));
  SMDFFHQX1 \fifo_reg[5][22] (.CK (clk), .D0 (\fifo[5] [22]), .D1
       (data_in[22]), .S0 (n_197), .SI (\fifo[5] [21]), .SE (SE), .Q
       (\fifo[5] [22]));
  SMDFFHQX1 \fifo_reg[4][2] (.CK (clk), .D0 (data_in[2]), .D1
       (\fifo[4] [2]), .S0 (n_196), .SI (\fifo[4] [1]), .SE (SE), .Q
       (\fifo[4] [2]));
  SMDFFHQX1 \fifo_reg[6][18] (.CK (clk), .D0 (data_in[18]), .D1
       (\fifo[6] [18]), .S0 (n_193), .SI (\fifo[6] [17]), .SE (SE), .Q
       (\fifo[6] [18]));
  SMDFFHQX1 \fifo_reg[4][18] (.CK (clk), .D0 (data_in[18]), .D1
       (\fifo[4] [18]), .S0 (n_196), .SI (\fifo[4] [17]), .SE (SE), .Q
       (\fifo[4] [18]));
  SMDFFHQX1 \fifo_reg[2][18] (.CK (clk), .D0 (data_in[18]), .D1
       (\fifo[2] [18]), .S0 (n_195), .SI (\fifo[2] [17]), .SE (SE), .Q
       (\fifo[2] [18]));
  SMDFFHQX1 \fifo_reg[5][18] (.CK (clk), .D0 (\fifo[5] [18]), .D1
       (data_in[18]), .S0 (n_197), .SI (\fifo[5] [17]), .SE (SE), .Q
       (\fifo[5] [18]));
  SMDFFHQX1 \fifo_reg[1][10] (.CK (clk), .D0 (data_in[10]), .D1
       (\fifo[1] [10]), .S0 (n_194), .SI (\fifo[1] [9]), .SE (SE), .Q
       (\fifo[1] [10]));
  SMDFFHQX1 \fifo_reg[4][6] (.CK (clk), .D0 (data_in[6]), .D1
       (\fifo[4] [6]), .S0 (n_196), .SI (\fifo[4] [5]), .SE (SE), .Q
       (\fifo[4] [6]));
  SMDFFHQX1 \fifo_reg[6][6] (.CK (clk), .D0 (data_in[6]), .D1
       (\fifo[6] [6]), .S0 (n_193), .SI (\fifo[6] [5]), .SE (SE), .Q
       (\fifo[6] [6]));
  SMDFFHQX1 \fifo_reg[6][10] (.CK (clk), .D0 (data_in[10]), .D1
       (\fifo[6] [10]), .S0 (n_193), .SI (\fifo[6] [9]), .SE (SE), .Q
       (\fifo[6] [10]));
  SMDFFHQX1 \fifo_reg[1][30] (.CK (clk), .D0 (data_in[30]), .D1
       (\fifo[1] [30]), .S0 (n_194), .SI (\fifo[1] [29]), .SE (SE), .Q
       (\fifo[1] [30]));
  SMDFFHQX1 \fifo_reg[1][2] (.CK (clk), .D0 (data_in[2]), .D1
       (\fifo[1] [2]), .S0 (n_194), .SI (\fifo[1] [1]), .SE (SE), .Q
       (\fifo[1] [2]));
  SMDFFHQX1 \fifo_reg[4][31] (.CK (clk), .D0 (data_in[31]), .D1
       (\fifo[4] [31]), .S0 (n_196), .SI (\fifo[4] [30]), .SE (SE), .Q
       (\fifo[4] [31]));
  SMDFFHQX1 \fifo_reg[4][30] (.CK (clk), .D0 (data_in[30]), .D1
       (\fifo[4] [30]), .S0 (n_196), .SI (\fifo[4] [29]), .SE (SE), .Q
       (\fifo[4] [30]));
  SMDFFHQX1 \fifo_reg[0][13] (.CK (clk), .D0 (data_in[13]), .D1
       (\fifo[0] [13]), .S0 (n_198), .SI (\fifo[0] [12]), .SE (SE), .Q
       (\fifo[0] [13]));
  SMDFFHQX1 \fifo_reg[4][29] (.CK (clk), .D0 (data_in[29]), .D1
       (\fifo[4] [29]), .S0 (n_196), .SI (\fifo[4] [28]), .SE (SE), .Q
       (\fifo[4] [29]));
  SMDFFHQX1 \fifo_reg[2][2] (.CK (clk), .D0 (data_in[2]), .D1
       (\fifo[2] [2]), .S0 (n_195), .SI (\fifo[2] [1]), .SE (SE), .Q
       (\fifo[2] [2]));
  SMDFFHQX1 \fifo_reg[2][0] (.CK (clk), .D0 (data_in[0]), .D1
       (\fifo[2] [0]), .S0 (n_195), .SI (\fifo[1] [31]), .SE (SE), .Q
       (\fifo[2] [0]));
  SMDFFHQX1 \fifo_reg[2][10] (.CK (clk), .D0 (data_in[10]), .D1
       (\fifo[2] [10]), .S0 (n_195), .SI (\fifo[2] [9]), .SE (SE), .Q
       (\fifo[2] [10]));
  SMDFFHQX1 \fifo_reg[0][12] (.CK (clk), .D0 (data_in[12]), .D1
       (\fifo[0] [12]), .S0 (n_198), .SI (\fifo[0] [11]), .SE (SE), .Q
       (\fifo[0] [12]));
  SMDFFHQX1 \fifo_reg[0][14] (.CK (clk), .D0 (data_in[14]), .D1
       (\fifo[0] [14]), .S0 (n_198), .SI (\fifo[0] [13]), .SE (SE), .Q
       (\fifo[0] [14]));
  SMDFFHQX1 \fifo_reg[0][15] (.CK (clk), .D0 (data_in[15]), .D1
       (\fifo[0] [15]), .S0 (n_198), .SI (\fifo[0] [14]), .SE (SE), .Q
       (\fifo[0] [15]));
  SMDFFHQX1 \fifo_reg[0][16] (.CK (clk), .D0 (data_in[16]), .D1
       (\fifo[0] [16]), .S0 (n_198), .SI (\fifo[0] [15]), .SE (SE), .Q
       (\fifo[0] [16]));
  SMDFFHQX1 \fifo_reg[0][17] (.CK (clk), .D0 (data_in[17]), .D1
       (\fifo[0] [17]), .S0 (n_198), .SI (\fifo[0] [16]), .SE (SE), .Q
       (\fifo[0] [17]));
  SMDFFHQX1 \fifo_reg[0][19] (.CK (clk), .D0 (data_in[19]), .D1
       (\fifo[0] [19]), .S0 (n_198), .SI (\fifo[0] [18]), .SE (SE), .Q
       (\fifo[0] [19]));
  SMDFFHQX1 \fifo_reg[0][20] (.CK (clk), .D0 (data_in[20]), .D1
       (\fifo[0] [20]), .S0 (n_198), .SI (\fifo[0] [19]), .SE (SE), .Q
       (\fifo[0] [20]));
  SMDFFHQX1 \fifo_reg[0][21] (.CK (clk), .D0 (data_in[21]), .D1
       (\fifo[0] [21]), .S0 (n_198), .SI (\fifo[0] [20]), .SE (SE), .Q
       (\fifo[0] [21]));
  SMDFFHQX1 \fifo_reg[5][2] (.CK (clk), .D0 (\fifo[5] [2]), .D1
       (data_in[2]), .S0 (n_197), .SI (\fifo[5] [1]), .SE (SE), .Q
       (\fifo[5] [2]));
  SMDFFHQX1 \fifo_reg[0][24] (.CK (clk), .D0 (data_in[24]), .D1
       (\fifo[0] [24]), .S0 (n_198), .SI (\fifo[0] [23]), .SE (SE), .Q
       (\fifo[0] [24]));
  SMDFFHQX1 \fifo_reg[0][25] (.CK (clk), .D0 (data_in[25]), .D1
       (\fifo[0] [25]), .S0 (n_198), .SI (\fifo[0] [24]), .SE (SE), .Q
       (\fifo[0] [25]));
  SMDFFHQX1 \fifo_reg[0][26] (.CK (clk), .D0 (data_in[26]), .D1
       (\fifo[0] [26]), .S0 (n_198), .SI (\fifo[0] [25]), .SE (SE), .Q
       (\fifo[0] [26]));
  SMDFFHQX1 \fifo_reg[0][27] (.CK (clk), .D0 (data_in[27]), .D1
       (\fifo[0] [27]), .S0 (n_198), .SI (\fifo[0] [26]), .SE (SE), .Q
       (\fifo[0] [27]));
  SMDFFHQX1 \fifo_reg[0][28] (.CK (clk), .D0 (data_in[28]), .D1
       (\fifo[0] [28]), .S0 (n_198), .SI (\fifo[0] [27]), .SE (SE), .Q
       (\fifo[0] [28]));
  SMDFFHQX1 \fifo_reg[0][29] (.CK (clk), .D0 (data_in[29]), .D1
       (\fifo[0] [29]), .S0 (n_198), .SI (\fifo[0] [28]), .SE (SE), .Q
       (\fifo[0] [29]));
  SMDFFHQX1 \fifo_reg[0][31] (.CK (clk), .D0 (data_in[31]), .D1
       (\fifo[0] [31]), .S0 (n_198), .SI (\fifo[0] [30]), .SE (SE), .Q
       (\fifo[0] [31]));
  SMDFFHQX1 \fifo_reg[0][0] (.CK (clk), .D0 (data_in[0]), .D1
       (\fifo[0] [0]), .S0 (n_198), .SI (data_out[31]), .SE (SE), .Q
       (\fifo[0] [0]));
  SMDFFHQX1 \fifo_reg[0][1] (.CK (clk), .D0 (data_in[1]), .D1
       (\fifo[0] [1]), .S0 (n_198), .SI (\fifo[0] [0]), .SE (SE), .Q
       (\fifo[0] [1]));
  SMDFFHQX1 \fifo_reg[0][3] (.CK (clk), .D0 (data_in[3]), .D1
       (\fifo[0] [3]), .S0 (n_198), .SI (\fifo[0] [2]), .SE (SE), .Q
       (\fifo[0] [3]));
  SMDFFHQX1 \fifo_reg[0][4] (.CK (clk), .D0 (data_in[4]), .D1
       (\fifo[0] [4]), .S0 (n_198), .SI (\fifo[0] [3]), .SE (SE), .Q
       (\fifo[0] [4]));
  SMDFFHQX1 \fifo_reg[0][5] (.CK (clk), .D0 (data_in[5]), .D1
       (\fifo[0] [5]), .S0 (n_198), .SI (\fifo[0] [4]), .SE (SE), .Q
       (\fifo[0] [5]));
  SMDFFHQX1 \fifo_reg[4][10] (.CK (clk), .D0 (data_in[10]), .D1
       (\fifo[4] [10]), .S0 (n_196), .SI (\fifo[4] [9]), .SE (SE), .Q
       (\fifo[4] [10]));
  SMDFFHQX1 \fifo_reg[0][7] (.CK (clk), .D0 (data_in[7]), .D1
       (\fifo[0] [7]), .S0 (n_198), .SI (\fifo[0] [6]), .SE (SE), .Q
       (\fifo[0] [7]));
  SMDFFHQX1 \fifo_reg[0][8] (.CK (clk), .D0 (data_in[8]), .D1
       (\fifo[0] [8]), .S0 (n_198), .SI (\fifo[0] [7]), .SE (SE), .Q
       (\fifo[0] [8]));
  SMDFFHQX1 \fifo_reg[0][9] (.CK (clk), .D0 (data_in[9]), .D1
       (\fifo[0] [9]), .S0 (n_198), .SI (\fifo[0] [8]), .SE (SE), .Q
       (\fifo[0] [9]));
  SMDFFHQX1 \fifo_reg[0][10] (.CK (clk), .D0 (data_in[10]), .D1
       (\fifo[0] [10]), .S0 (n_198), .SI (\fifo[0] [9]), .SE (SE), .Q
       (\fifo[0] [10]));
  SMDFFHQX1 \fifo_reg[0][11] (.CK (clk), .D0 (data_in[11]), .D1
       (\fifo[0] [11]), .S0 (n_198), .SI (\fifo[0] [10]), .SE (SE), .Q
       (\fifo[0] [11]));
  SMDFFHQX1 \fifo_reg[4][0] (.CK (clk), .D0 (data_in[0]), .D1
       (\fifo[4] [0]), .S0 (n_196), .SI (\fifo[3] [31]), .SE (SE), .Q
       (\fifo[4] [0]));
  SMDFFHQX1 \fifo_reg[4][1] (.CK (clk), .D0 (data_in[1]), .D1
       (\fifo[4] [1]), .S0 (n_196), .SI (\fifo[4] [0]), .SE (SE), .Q
       (\fifo[4] [1]));
  SMDFFHQX1 \fifo_reg[4][3] (.CK (clk), .D0 (data_in[3]), .D1
       (\fifo[4] [3]), .S0 (n_196), .SI (\fifo[4] [2]), .SE (SE), .Q
       (\fifo[4] [3]));
  SMDFFHQX1 \fifo_reg[4][4] (.CK (clk), .D0 (data_in[4]), .D1
       (\fifo[4] [4]), .S0 (n_196), .SI (\fifo[4] [3]), .SE (SE), .Q
       (\fifo[4] [4]));
  SMDFFHQX1 \fifo_reg[4][5] (.CK (clk), .D0 (data_in[5]), .D1
       (\fifo[4] [5]), .S0 (n_196), .SI (\fifo[4] [4]), .SE (SE), .Q
       (\fifo[4] [5]));
  SMDFFHQX1 \fifo_reg[4][7] (.CK (clk), .D0 (data_in[7]), .D1
       (\fifo[4] [7]), .S0 (n_196), .SI (\fifo[4] [6]), .SE (SE), .Q
       (\fifo[4] [7]));
  SMDFFHQX1 \fifo_reg[4][8] (.CK (clk), .D0 (data_in[8]), .D1
       (\fifo[4] [8]), .S0 (n_196), .SI (\fifo[4] [7]), .SE (SE), .Q
       (\fifo[4] [8]));
  SMDFFHQX1 \fifo_reg[4][9] (.CK (clk), .D0 (data_in[9]), .D1
       (\fifo[4] [9]), .S0 (n_196), .SI (\fifo[4] [8]), .SE (SE), .Q
       (\fifo[4] [9]));
  SMDFFHQX1 \fifo_reg[4][11] (.CK (clk), .D0 (data_in[11]), .D1
       (\fifo[4] [11]), .S0 (n_196), .SI (\fifo[4] [10]), .SE (SE), .Q
       (\fifo[4] [11]));
  SMDFFHQX1 \fifo_reg[4][12] (.CK (clk), .D0 (data_in[12]), .D1
       (\fifo[4] [12]), .S0 (n_196), .SI (\fifo[4] [11]), .SE (SE), .Q
       (\fifo[4] [12]));
  SMDFFHQX1 \fifo_reg[4][13] (.CK (clk), .D0 (data_in[13]), .D1
       (\fifo[4] [13]), .S0 (n_196), .SI (\fifo[4] [12]), .SE (SE), .Q
       (\fifo[4] [13]));
  SMDFFHQX1 \fifo_reg[4][14] (.CK (clk), .D0 (data_in[14]), .D1
       (\fifo[4] [14]), .S0 (n_196), .SI (\fifo[4] [13]), .SE (SE), .Q
       (\fifo[4] [14]));
  SMDFFHQX1 \fifo_reg[4][15] (.CK (clk), .D0 (data_in[15]), .D1
       (\fifo[4] [15]), .S0 (n_196), .SI (\fifo[4] [14]), .SE (SE), .Q
       (\fifo[4] [15]));
  SMDFFHQX1 \fifo_reg[4][16] (.CK (clk), .D0 (data_in[16]), .D1
       (\fifo[4] [16]), .S0 (n_196), .SI (\fifo[4] [15]), .SE (SE), .Q
       (\fifo[4] [16]));
  SMDFFHQX1 \fifo_reg[4][17] (.CK (clk), .D0 (data_in[17]), .D1
       (\fifo[4] [17]), .S0 (n_196), .SI (\fifo[4] [16]), .SE (SE), .Q
       (\fifo[4] [17]));
  SMDFFHQX1 \fifo_reg[4][19] (.CK (clk), .D0 (data_in[19]), .D1
       (\fifo[4] [19]), .S0 (n_196), .SI (\fifo[4] [18]), .SE (SE), .Q
       (\fifo[4] [19]));
  SMDFFHQX1 \fifo_reg[4][20] (.CK (clk), .D0 (data_in[20]), .D1
       (\fifo[4] [20]), .S0 (n_196), .SI (\fifo[4] [19]), .SE (SE), .Q
       (\fifo[4] [20]));
  SMDFFHQX1 \fifo_reg[4][21] (.CK (clk), .D0 (data_in[21]), .D1
       (\fifo[4] [21]), .S0 (n_196), .SI (\fifo[4] [20]), .SE (SE), .Q
       (\fifo[4] [21]));
  SMDFFHQX1 \fifo_reg[4][23] (.CK (clk), .D0 (data_in[23]), .D1
       (\fifo[4] [23]), .S0 (n_196), .SI (\fifo[4] [22]), .SE (SE), .Q
       (\fifo[4] [23]));
  SMDFFHQX1 \fifo_reg[4][24] (.CK (clk), .D0 (data_in[24]), .D1
       (\fifo[4] [24]), .S0 (n_196), .SI (\fifo[4] [23]), .SE (SE), .Q
       (\fifo[4] [24]));
  SMDFFHQX1 \fifo_reg[4][25] (.CK (clk), .D0 (data_in[25]), .D1
       (\fifo[4] [25]), .S0 (n_196), .SI (\fifo[4] [24]), .SE (SE), .Q
       (\fifo[4] [25]));
  SMDFFHQX1 \fifo_reg[4][27] (.CK (clk), .D0 (data_in[27]), .D1
       (\fifo[4] [27]), .S0 (n_196), .SI (\fifo[4] [26]), .SE (SE), .Q
       (\fifo[4] [27]));
  SMDFFHQX1 \fifo_reg[4][28] (.CK (clk), .D0 (data_in[28]), .D1
       (\fifo[4] [28]), .S0 (n_196), .SI (\fifo[4] [27]), .SE (SE), .Q
       (\fifo[4] [28]));
  SDFFRHQX1 \read_pointer_reg[3] (.RN (rst_n), .CK (clk), .D (n_82),
       .SI (read_pointer[2]), .SE (SE), .Q (read_pointer[3]));
  SDFFRHQX1 \write_pointer_reg[3] (.RN (rst_n), .CK (clk), .D (n_84),
       .SI (write_pointer[2]), .SE (SE), .Q (write_pointer[3]));
  SDFFRHQX1 \read_pointer_reg[2] (.RN (rst_n), .CK (clk), .D (n_79),
       .SI (read_pointer[1]), .SE (SE), .Q (read_pointer[2]));
  SDFFRHQX1 \write_pointer_reg[1] (.RN (rst_n), .CK (clk), .D (n_77),
       .SI (write_pointer[0]), .SE (SE), .Q (write_pointer[1]));
  SDFFRHQX1 \read_pointer_reg[0] (.RN (rst_n), .CK (clk), .D (n_83),
       .SI (\fifo[7] [31]), .SE (SE), .Q (read_pointer[0]));
  SDFFRHQX1 \read_pointer_reg[1] (.RN (rst_n), .CK (clk), .D (n_80),
       .SI (read_pointer[0]), .SE (SE), .Q (read_pointer[1]));
  NAND2XL g7701__5477(.A (n_73), .B (n_167), .Y (n_192));
  NAND2XL g7700__2398(.A (n_74), .B (n_169), .Y (n_191));
  NAND2XL g7699__5107(.A (n_130), .B (n_172), .Y (n_190));
  NAND2XL g7698__6260(.A (n_132), .B (n_173), .Y (n_189));
  NAND2XL g7697__4319(.A (n_129), .B (n_168), .Y (n_188));
  NAND2XL g7696__8428(.A (n_111), .B (n_161), .Y (n_187));
  NAND2XL g7695__5526(.A (n_72), .B (n_163), .Y (n_186));
  NAND2XL g7693__6783(.A (n_166), .B (n_124), .Y (n_185));
  NAND2XL g7692__3680(.A (n_117), .B (n_162), .Y (n_184));
  NAND2XL g7691__1617(.A (n_133), .B (n_164), .Y (n_183));
  SMDFFHQX1 \fifo_reg[2][15] (.CK (clk), .D0 (data_in[15]), .D1
       (\fifo[2] [15]), .S0 (n_195), .SI (\fifo[2] [14]), .SE (SE), .Q
       (\fifo[2] [15]));
  SMDFFHQX1 \fifo_reg[2][16] (.CK (clk), .D0 (data_in[16]), .D1
       (\fifo[2] [16]), .S0 (n_195), .SI (\fifo[2] [15]), .SE (SE), .Q
       (\fifo[2] [16]));
  SMDFFHQX1 \fifo_reg[2][17] (.CK (clk), .D0 (data_in[17]), .D1
       (\fifo[2] [17]), .S0 (n_195), .SI (\fifo[2] [16]), .SE (SE), .Q
       (\fifo[2] [17]));
  SMDFFHQX1 \fifo_reg[2][19] (.CK (clk), .D0 (data_in[19]), .D1
       (\fifo[2] [19]), .S0 (n_195), .SI (\fifo[2] [18]), .SE (SE), .Q
       (\fifo[2] [19]));
  SMDFFHQX1 \fifo_reg[2][20] (.CK (clk), .D0 (data_in[20]), .D1
       (\fifo[2] [20]), .S0 (n_195), .SI (\fifo[2] [19]), .SE (SE), .Q
       (\fifo[2] [20]));
  SMDFFHQX1 \fifo_reg[2][21] (.CK (clk), .D0 (data_in[21]), .D1
       (\fifo[2] [21]), .S0 (n_195), .SI (\fifo[2] [20]), .SE (SE), .Q
       (\fifo[2] [21]));
  SMDFFHQX1 \fifo_reg[2][23] (.CK (clk), .D0 (data_in[23]), .D1
       (\fifo[2] [23]), .S0 (n_195), .SI (\fifo[2] [22]), .SE (SE), .Q
       (\fifo[2] [23]));
  SMDFFHQX1 \fifo_reg[2][24] (.CK (clk), .D0 (data_in[24]), .D1
       (\fifo[2] [24]), .S0 (n_195), .SI (\fifo[2] [23]), .SE (SE), .Q
       (\fifo[2] [24]));
  SMDFFHQX1 \fifo_reg[2][25] (.CK (clk), .D0 (data_in[25]), .D1
       (\fifo[2] [25]), .S0 (n_195), .SI (\fifo[2] [24]), .SE (SE), .Q
       (\fifo[2] [25]));
  SMDFFHQX1 \fifo_reg[2][27] (.CK (clk), .D0 (data_in[27]), .D1
       (\fifo[2] [27]), .S0 (n_195), .SI (\fifo[2] [26]), .SE (SE), .Q
       (\fifo[2] [27]));
  SMDFFHQX1 \fifo_reg[2][28] (.CK (clk), .D0 (data_in[28]), .D1
       (\fifo[2] [28]), .S0 (n_195), .SI (\fifo[2] [27]), .SE (SE), .Q
       (\fifo[2] [28]));
  SMDFFHQX1 \fifo_reg[2][29] (.CK (clk), .D0 (data_in[29]), .D1
       (\fifo[2] [29]), .S0 (n_195), .SI (\fifo[2] [28]), .SE (SE), .Q
       (\fifo[2] [29]));
  SMDFFHQX1 \fifo_reg[2][30] (.CK (clk), .D0 (data_in[30]), .D1
       (\fifo[2] [30]), .S0 (n_195), .SI (\fifo[2] [29]), .SE (SE), .Q
       (\fifo[2] [30]));
  SMDFFHQX1 \fifo_reg[2][31] (.CK (clk), .D0 (data_in[31]), .D1
       (\fifo[2] [31]), .S0 (n_195), .SI (\fifo[2] [30]), .SE (SE), .Q
       (\fifo[2] [31]));
  SMDFFHQX1 \fifo_reg[6][0] (.CK (clk), .D0 (data_in[0]), .D1
       (\fifo[6] [0]), .S0 (n_193), .SI (\fifo[5] [31]), .SE (SE), .Q
       (\fifo[6] [0]));
  SMDFFHQX1 \fifo_reg[6][1] (.CK (clk), .D0 (data_in[1]), .D1
       (\fifo[6] [1]), .S0 (n_193), .SI (\fifo[6] [0]), .SE (SE), .Q
       (\fifo[6] [1]));
  SMDFFHQX1 \fifo_reg[6][3] (.CK (clk), .D0 (data_in[3]), .D1
       (\fifo[6] [3]), .S0 (n_193), .SI (\fifo[6] [2]), .SE (SE), .Q
       (\fifo[6] [3]));
  SMDFFHQX1 \fifo_reg[6][4] (.CK (clk), .D0 (data_in[4]), .D1
       (\fifo[6] [4]), .S0 (n_193), .SI (\fifo[6] [3]), .SE (SE), .Q
       (\fifo[6] [4]));
  SMDFFHQX1 \fifo_reg[6][5] (.CK (clk), .D0 (data_in[5]), .D1
       (\fifo[6] [5]), .S0 (n_193), .SI (\fifo[6] [4]), .SE (SE), .Q
       (\fifo[6] [5]));
  SMDFFHQX1 \fifo_reg[6][7] (.CK (clk), .D0 (data_in[7]), .D1
       (\fifo[6] [7]), .S0 (n_193), .SI (\fifo[6] [6]), .SE (SE), .Q
       (\fifo[6] [7]));
  SMDFFHQX1 \fifo_reg[6][8] (.CK (clk), .D0 (data_in[8]), .D1
       (\fifo[6] [8]), .S0 (n_193), .SI (\fifo[6] [7]), .SE (SE), .Q
       (\fifo[6] [8]));
  SMDFFHQX1 \fifo_reg[6][9] (.CK (clk), .D0 (data_in[9]), .D1
       (\fifo[6] [9]), .S0 (n_193), .SI (\fifo[6] [8]), .SE (SE), .Q
       (\fifo[6] [9]));
  SMDFFHQX1 \fifo_reg[6][11] (.CK (clk), .D0 (data_in[11]), .D1
       (\fifo[6] [11]), .S0 (n_193), .SI (\fifo[6] [10]), .SE (SE), .Q
       (\fifo[6] [11]));
  SMDFFHQX1 \fifo_reg[6][12] (.CK (clk), .D0 (data_in[12]), .D1
       (\fifo[6] [12]), .S0 (n_193), .SI (\fifo[6] [11]), .SE (SE), .Q
       (\fifo[6] [12]));
  SMDFFHQX1 \fifo_reg[6][13] (.CK (clk), .D0 (data_in[13]), .D1
       (\fifo[6] [13]), .S0 (n_193), .SI (\fifo[6] [12]), .SE (SE), .Q
       (\fifo[6] [13]));
  SMDFFHQX1 \fifo_reg[6][14] (.CK (clk), .D0 (data_in[14]), .D1
       (\fifo[6] [14]), .S0 (n_193), .SI (\fifo[6] [13]), .SE (SE), .Q
       (\fifo[6] [14]));
  SMDFFHQX1 \fifo_reg[6][15] (.CK (clk), .D0 (data_in[15]), .D1
       (\fifo[6] [15]), .S0 (n_193), .SI (\fifo[6] [14]), .SE (SE), .Q
       (\fifo[6] [15]));
  SMDFFHQX1 \fifo_reg[6][16] (.CK (clk), .D0 (data_in[16]), .D1
       (\fifo[6] [16]), .S0 (n_193), .SI (\fifo[6] [15]), .SE (SE), .Q
       (\fifo[6] [16]));
  SMDFFHQX1 \fifo_reg[6][17] (.CK (clk), .D0 (data_in[17]), .D1
       (\fifo[6] [17]), .S0 (n_193), .SI (\fifo[6] [16]), .SE (SE), .Q
       (\fifo[6] [17]));
  SMDFFHQX1 \fifo_reg[6][19] (.CK (clk), .D0 (data_in[19]), .D1
       (\fifo[6] [19]), .S0 (n_193), .SI (\fifo[6] [18]), .SE (SE), .Q
       (\fifo[6] [19]));
  SMDFFHQX1 \fifo_reg[6][20] (.CK (clk), .D0 (data_in[20]), .D1
       (\fifo[6] [20]), .S0 (n_193), .SI (\fifo[6] [19]), .SE (SE), .Q
       (\fifo[6] [20]));
  SMDFFHQX1 \fifo_reg[6][21] (.CK (clk), .D0 (data_in[21]), .D1
       (\fifo[6] [21]), .S0 (n_193), .SI (\fifo[6] [20]), .SE (SE), .Q
       (\fifo[6] [21]));
  SMDFFHQX1 \fifo_reg[6][23] (.CK (clk), .D0 (data_in[23]), .D1
       (\fifo[6] [23]), .S0 (n_193), .SI (\fifo[6] [22]), .SE (SE), .Q
       (\fifo[6] [23]));
  SMDFFHQX1 \fifo_reg[6][24] (.CK (clk), .D0 (data_in[24]), .D1
       (\fifo[6] [24]), .S0 (n_193), .SI (\fifo[6] [23]), .SE (SE), .Q
       (\fifo[6] [24]));
  SMDFFHQX1 \fifo_reg[6][25] (.CK (clk), .D0 (data_in[25]), .D1
       (\fifo[6] [25]), .S0 (n_193), .SI (\fifo[6] [24]), .SE (SE), .Q
       (\fifo[6] [25]));
  SMDFFHQX1 \fifo_reg[2][14] (.CK (clk), .D0 (data_in[14]), .D1
       (\fifo[2] [14]), .S0 (n_195), .SI (\fifo[2] [13]), .SE (SE), .Q
       (\fifo[2] [14]));
  SMDFFHQX1 \fifo_reg[6][27] (.CK (clk), .D0 (data_in[27]), .D1
       (\fifo[6] [27]), .S0 (n_193), .SI (\fifo[6] [26]), .SE (SE), .Q
       (\fifo[6] [27]));
  SMDFFHQX1 \fifo_reg[6][28] (.CK (clk), .D0 (data_in[28]), .D1
       (\fifo[6] [28]), .S0 (n_193), .SI (\fifo[6] [27]), .SE (SE), .Q
       (\fifo[6] [28]));
  SMDFFHQX1 \fifo_reg[6][29] (.CK (clk), .D0 (data_in[29]), .D1
       (\fifo[6] [29]), .S0 (n_193), .SI (\fifo[6] [28]), .SE (SE), .Q
       (\fifo[6] [29]));
  SMDFFHQX1 \fifo_reg[6][30] (.CK (clk), .D0 (data_in[30]), .D1
       (\fifo[6] [30]), .S0 (n_193), .SI (\fifo[6] [29]), .SE (SE), .Q
       (\fifo[6] [30]));
  SMDFFHQX1 \fifo_reg[6][31] (.CK (clk), .D0 (data_in[31]), .D1
       (\fifo[6] [31]), .S0 (n_193), .SI (\fifo[6] [30]), .SE (SE), .Q
       (\fifo[6] [31]));
  SMDFFHQX1 \fifo_reg[1][0] (.CK (clk), .D0 (data_in[0]), .D1
       (\fifo[1] [0]), .S0 (n_194), .SI (\fifo[0] [31]), .SE (SE), .Q
       (\fifo[1] [0]));
  SMDFFHQX1 \fifo_reg[1][1] (.CK (clk), .D0 (data_in[1]), .D1
       (\fifo[1] [1]), .S0 (n_194), .SI (\fifo[1] [0]), .SE (SE), .Q
       (\fifo[1] [1]));
  SMDFFHQX1 \fifo_reg[1][3] (.CK (clk), .D0 (data_in[3]), .D1
       (\fifo[1] [3]), .S0 (n_194), .SI (\fifo[1] [2]), .SE (SE), .Q
       (\fifo[1] [3]));
  SMDFFHQX1 \fifo_reg[1][4] (.CK (clk), .D0 (data_in[4]), .D1
       (\fifo[1] [4]), .S0 (n_194), .SI (\fifo[1] [3]), .SE (SE), .Q
       (\fifo[1] [4]));
  SMDFFHQX1 \fifo_reg[1][5] (.CK (clk), .D0 (data_in[5]), .D1
       (\fifo[1] [5]), .S0 (n_194), .SI (\fifo[1] [4]), .SE (SE), .Q
       (\fifo[1] [5]));
  SMDFFHQX1 \fifo_reg[1][7] (.CK (clk), .D0 (data_in[7]), .D1
       (\fifo[1] [7]), .S0 (n_194), .SI (\fifo[1] [6]), .SE (SE), .Q
       (\fifo[1] [7]));
  SMDFFHQX1 \fifo_reg[1][8] (.CK (clk), .D0 (data_in[8]), .D1
       (\fifo[1] [8]), .S0 (n_194), .SI (\fifo[1] [7]), .SE (SE), .Q
       (\fifo[1] [8]));
  SMDFFHQX1 \fifo_reg[1][9] (.CK (clk), .D0 (data_in[9]), .D1
       (\fifo[1] [9]), .S0 (n_194), .SI (\fifo[1] [8]), .SE (SE), .Q
       (\fifo[1] [9]));
  SMDFFHQX1 \fifo_reg[1][11] (.CK (clk), .D0 (data_in[11]), .D1
       (\fifo[1] [11]), .S0 (n_194), .SI (\fifo[1] [10]), .SE (SE), .Q
       (\fifo[1] [11]));
  SMDFFHQX1 \fifo_reg[1][12] (.CK (clk), .D0 (data_in[12]), .D1
       (\fifo[1] [12]), .S0 (n_194), .SI (\fifo[1] [11]), .SE (SE), .Q
       (\fifo[1] [12]));
  SMDFFHQX1 \fifo_reg[1][13] (.CK (clk), .D0 (data_in[13]), .D1
       (\fifo[1] [13]), .S0 (n_194), .SI (\fifo[1] [12]), .SE (SE), .Q
       (\fifo[1] [13]));
  SMDFFHQX1 \fifo_reg[1][14] (.CK (clk), .D0 (data_in[14]), .D1
       (\fifo[1] [14]), .S0 (n_194), .SI (\fifo[1] [13]), .SE (SE), .Q
       (\fifo[1] [14]));
  SMDFFHQX1 \fifo_reg[1][15] (.CK (clk), .D0 (data_in[15]), .D1
       (\fifo[1] [15]), .S0 (n_194), .SI (\fifo[1] [14]), .SE (SE), .Q
       (\fifo[1] [15]));
  SMDFFHQX1 \fifo_reg[1][16] (.CK (clk), .D0 (data_in[16]), .D1
       (\fifo[1] [16]), .S0 (n_194), .SI (\fifo[1] [15]), .SE (SE), .Q
       (\fifo[1] [16]));
  SMDFFHQX1 \fifo_reg[1][17] (.CK (clk), .D0 (data_in[17]), .D1
       (\fifo[1] [17]), .S0 (n_194), .SI (\fifo[1] [16]), .SE (SE), .Q
       (\fifo[1] [17]));
  SMDFFHQX1 \fifo_reg[1][19] (.CK (clk), .D0 (data_in[19]), .D1
       (\fifo[1] [19]), .S0 (n_194), .SI (\fifo[1] [18]), .SE (SE), .Q
       (\fifo[1] [19]));
  SMDFFHQX1 \fifo_reg[5][0] (.CK (clk), .D0 (\fifo[5] [0]), .D1
       (data_in[0]), .S0 (n_197), .SI (\fifo[4] [31]), .SE (SE), .Q
       (\fifo[5] [0]));
  SMDFFHQX1 \fifo_reg[5][1] (.CK (clk), .D0 (\fifo[5] [1]), .D1
       (data_in[1]), .S0 (n_197), .SI (\fifo[5] [0]), .SE (SE), .Q
       (\fifo[5] [1]));
  SMDFFHQX1 \fifo_reg[1][6] (.CK (clk), .D0 (data_in[6]), .D1
       (\fifo[1] [6]), .S0 (n_194), .SI (\fifo[1] [5]), .SE (SE), .Q
       (\fifo[1] [6]));
  SMDFFHQX1 \fifo_reg[2][13] (.CK (clk), .D0 (data_in[13]), .D1
       (\fifo[2] [13]), .S0 (n_195), .SI (\fifo[2] [12]), .SE (SE), .Q
       (\fifo[2] [13]));
  SMDFFHQX1 \fifo_reg[5][3] (.CK (clk), .D0 (\fifo[5] [3]), .D1
       (data_in[3]), .S0 (n_197), .SI (\fifo[5] [2]), .SE (SE), .Q
       (\fifo[5] [3]));
  SMDFFHQX1 \fifo_reg[5][4] (.CK (clk), .D0 (\fifo[5] [4]), .D1
       (data_in[4]), .S0 (n_197), .SI (\fifo[5] [3]), .SE (SE), .Q
       (\fifo[5] [4]));
  SMDFFHQX1 \fifo_reg[5][5] (.CK (clk), .D0 (\fifo[5] [5]), .D1
       (data_in[5]), .S0 (n_197), .SI (\fifo[5] [4]), .SE (SE), .Q
       (\fifo[5] [5]));
  SMDFFHQX1 \fifo_reg[5][7] (.CK (clk), .D0 (\fifo[5] [7]), .D1
       (data_in[7]), .S0 (n_197), .SI (\fifo[5] [6]), .SE (SE), .Q
       (\fifo[5] [7]));
  SMDFFHQX1 \fifo_reg[5][8] (.CK (clk), .D0 (\fifo[5] [8]), .D1
       (data_in[8]), .S0 (n_197), .SI (\fifo[5] [7]), .SE (SE), .Q
       (\fifo[5] [8]));
  SMDFFHQX1 \fifo_reg[5][9] (.CK (clk), .D0 (\fifo[5] [9]), .D1
       (data_in[9]), .S0 (n_197), .SI (\fifo[5] [8]), .SE (SE), .Q
       (\fifo[5] [9]));
  SMDFFHQX1 \fifo_reg[5][11] (.CK (clk), .D0 (\fifo[5] [11]), .D1
       (data_in[11]), .S0 (n_197), .SI (\fifo[5] [10]), .SE (SE), .Q
       (\fifo[5] [11]));
  SMDFFHQX1 \fifo_reg[5][12] (.CK (clk), .D0 (\fifo[5] [12]), .D1
       (data_in[12]), .S0 (n_197), .SI (\fifo[5] [11]), .SE (SE), .Q
       (\fifo[5] [12]));
  SMDFFHQX1 \fifo_reg[5][13] (.CK (clk), .D0 (\fifo[5] [13]), .D1
       (data_in[13]), .S0 (n_197), .SI (\fifo[5] [12]), .SE (SE), .Q
       (\fifo[5] [13]));
  SMDFFHQX1 \fifo_reg[5][15] (.CK (clk), .D0 (\fifo[5] [15]), .D1
       (data_in[15]), .S0 (n_197), .SI (\fifo[5] [14]), .SE (SE), .Q
       (\fifo[5] [15]));
  SMDFFHQX1 \fifo_reg[5][16] (.CK (clk), .D0 (\fifo[5] [16]), .D1
       (data_in[16]), .S0 (n_197), .SI (\fifo[5] [15]), .SE (SE), .Q
       (\fifo[5] [16]));
  SMDFFHQX1 \fifo_reg[5][17] (.CK (clk), .D0 (\fifo[5] [17]), .D1
       (data_in[17]), .S0 (n_197), .SI (\fifo[5] [16]), .SE (SE), .Q
       (\fifo[5] [17]));
  SMDFFHQX1 \fifo_reg[2][12] (.CK (clk), .D0 (data_in[12]), .D1
       (\fifo[2] [12]), .S0 (n_195), .SI (\fifo[2] [11]), .SE (SE), .Q
       (\fifo[2] [12]));
  SMDFFHQX1 \fifo_reg[5][19] (.CK (clk), .D0 (\fifo[5] [19]), .D1
       (data_in[19]), .S0 (n_197), .SI (\fifo[5] [18]), .SE (SE), .Q
       (\fifo[5] [19]));
  SMDFFHQX1 \fifo_reg[5][20] (.CK (clk), .D0 (\fifo[5] [20]), .D1
       (data_in[20]), .S0 (n_197), .SI (\fifo[5] [19]), .SE (SE), .Q
       (\fifo[5] [20]));
  SMDFFHQX1 \fifo_reg[5][21] (.CK (clk), .D0 (\fifo[5] [21]), .D1
       (data_in[21]), .S0 (n_197), .SI (\fifo[5] [20]), .SE (SE), .Q
       (\fifo[5] [21]));
  SMDFFHQX1 \fifo_reg[5][23] (.CK (clk), .D0 (\fifo[5] [23]), .D1
       (data_in[23]), .S0 (n_197), .SI (\fifo[5] [22]), .SE (SE), .Q
       (\fifo[5] [23]));
  SMDFFHQX1 \fifo_reg[5][24] (.CK (clk), .D0 (\fifo[5] [24]), .D1
       (data_in[24]), .S0 (n_197), .SI (\fifo[5] [23]), .SE (SE), .Q
       (\fifo[5] [24]));
  SMDFFHQX1 \fifo_reg[5][25] (.CK (clk), .D0 (\fifo[5] [25]), .D1
       (data_in[25]), .S0 (n_197), .SI (\fifo[5] [24]), .SE (SE), .Q
       (\fifo[5] [25]));
  SMDFFHQX1 \fifo_reg[5][27] (.CK (clk), .D0 (\fifo[5] [27]), .D1
       (data_in[27]), .S0 (n_197), .SI (\fifo[5] [26]), .SE (SE), .Q
       (\fifo[5] [27]));
  SMDFFHQX1 \fifo_reg[5][28] (.CK (clk), .D0 (\fifo[5] [28]), .D1
       (data_in[28]), .S0 (n_197), .SI (\fifo[5] [27]), .SE (SE), .Q
       (\fifo[5] [28]));
  SMDFFHQX1 \fifo_reg[5][29] (.CK (clk), .D0 (\fifo[5] [29]), .D1
       (data_in[29]), .S0 (n_197), .SI (\fifo[5] [28]), .SE (SE), .Q
       (\fifo[5] [29]));
  SMDFFHQX1 \fifo_reg[5][31] (.CK (clk), .D0 (\fifo[5] [31]), .D1
       (data_in[31]), .S0 (n_197), .SI (\fifo[5] [30]), .SE (SE), .Q
       (\fifo[5] [31]));
  SMDFFHQX1 \fifo_reg[5][14] (.CK (clk), .D0 (\fifo[5] [14]), .D1
       (data_in[14]), .S0 (n_197), .SI (\fifo[5] [13]), .SE (SE), .Q
       (\fifo[5] [14]));
  SMDFFHQX1 \fifo_reg[5][30] (.CK (clk), .D0 (\fifo[5] [30]), .D1
       (data_in[30]), .S0 (n_197), .SI (\fifo[5] [29]), .SE (SE), .Q
       (\fifo[5] [30]));
  SMDFFHQX1 \fifo_reg[1][21] (.CK (clk), .D0 (data_in[21]), .D1
       (\fifo[1] [21]), .S0 (n_194), .SI (\fifo[1] [20]), .SE (SE), .Q
       (\fifo[1] [21]));
  SMDFFHQX1 \fifo_reg[1][22] (.CK (clk), .D0 (data_in[22]), .D1
       (\fifo[1] [22]), .S0 (n_194), .SI (\fifo[1] [21]), .SE (SE), .Q
       (\fifo[1] [22]));
  SMDFFHQX1 \fifo_reg[2][11] (.CK (clk), .D0 (data_in[11]), .D1
       (\fifo[2] [11]), .S0 (n_195), .SI (\fifo[2] [10]), .SE (SE), .Q
       (\fifo[2] [11]));
  SMDFFHQX1 \fifo_reg[1][23] (.CK (clk), .D0 (data_in[23]), .D1
       (\fifo[1] [23]), .S0 (n_194), .SI (\fifo[1] [22]), .SE (SE), .Q
       (\fifo[1] [23]));
  SMDFFHQX1 \fifo_reg[1][24] (.CK (clk), .D0 (data_in[24]), .D1
       (\fifo[1] [24]), .S0 (n_194), .SI (\fifo[1] [23]), .SE (SE), .Q
       (\fifo[1] [24]));
  SMDFFHQX1 \fifo_reg[1][25] (.CK (clk), .D0 (data_in[25]), .D1
       (\fifo[1] [25]), .S0 (n_194), .SI (\fifo[1] [24]), .SE (SE), .Q
       (\fifo[1] [25]));
  SMDFFHQX1 \fifo_reg[1][27] (.CK (clk), .D0 (data_in[27]), .D1
       (\fifo[1] [27]), .S0 (n_194), .SI (\fifo[1] [26]), .SE (SE), .Q
       (\fifo[1] [27]));
  SMDFFHQX1 \fifo_reg[1][28] (.CK (clk), .D0 (data_in[28]), .D1
       (\fifo[1] [28]), .S0 (n_194), .SI (\fifo[1] [27]), .SE (SE), .Q
       (\fifo[1] [28]));
  SMDFFHQX1 \fifo_reg[1][29] (.CK (clk), .D0 (data_in[29]), .D1
       (\fifo[1] [29]), .S0 (n_194), .SI (\fifo[1] [28]), .SE (SE), .Q
       (\fifo[1] [29]));
  SMDFFHQX1 \fifo_reg[1][31] (.CK (clk), .D0 (data_in[31]), .D1
       (\fifo[1] [31]), .S0 (n_194), .SI (\fifo[1] [30]), .SE (SE), .Q
       (\fifo[1] [31]));
  SMDFFHQX1 \fifo_reg[2][9] (.CK (clk), .D0 (data_in[9]), .D1
       (\fifo[2] [9]), .S0 (n_195), .SI (\fifo[2] [8]), .SE (SE), .Q
       (\fifo[2] [9]));
  SMDFFHQX1 \fifo_reg[2][8] (.CK (clk), .D0 (data_in[8]), .D1
       (\fifo[2] [8]), .S0 (n_195), .SI (\fifo[2] [7]), .SE (SE), .Q
       (\fifo[2] [8]));
  SMDFFHQX1 \fifo_reg[2][7] (.CK (clk), .D0 (data_in[7]), .D1
       (\fifo[2] [7]), .S0 (n_195), .SI (\fifo[2] [6]), .SE (SE), .Q
       (\fifo[2] [7]));
  SMDFFHQX1 \fifo_reg[2][6] (.CK (clk), .D0 (data_in[6]), .D1
       (\fifo[2] [6]), .S0 (n_195), .SI (\fifo[2] [5]), .SE (SE), .Q
       (\fifo[2] [6]));
  SMDFFHQX1 \fifo_reg[2][5] (.CK (clk), .D0 (data_in[5]), .D1
       (\fifo[2] [5]), .S0 (n_195), .SI (\fifo[2] [4]), .SE (SE), .Q
       (\fifo[2] [5]));
  SMDFFHQX1 \fifo_reg[2][4] (.CK (clk), .D0 (data_in[4]), .D1
       (\fifo[2] [4]), .S0 (n_195), .SI (\fifo[2] [3]), .SE (SE), .Q
       (\fifo[2] [4]));
  SMDFFHQX1 \fifo_reg[2][1] (.CK (clk), .D0 (data_in[1]), .D1
       (\fifo[2] [1]), .S0 (n_195), .SI (\fifo[2] [0]), .SE (SE), .Q
       (\fifo[2] [1]));
  SMDFFHQX1 \fifo_reg[2][3] (.CK (clk), .D0 (data_in[3]), .D1
       (\fifo[2] [3]), .S0 (n_195), .SI (\fifo[2] [2]), .SE (SE), .Q
       (\fifo[2] [3]));
  NAND2XL g7712__2802(.A (n_110), .B (n_142), .Y (n_182));
  NAND2XL g7719__1705(.A (n_140), .B (n_97), .Y (n_181));
  OAI2BB1X1 g7899__5122(.A0N (n_135), .A1N (write_pointer[2]), .B0
       (n_138), .Y (n_180));
  SMDFFHQX1 \fifo_reg[7][2] (.CK (clk), .D0 (\fifo[7] [2]), .D1
       (data_in[2]), .S0 (n_179), .SI (\fifo[7] [1]), .SE (SE), .Q
       (\fifo[7] [2]));
  SMDFFHQX1 \fifo_reg[7][10] (.CK (clk), .D0 (\fifo[7] [10]), .D1
       (data_in[10]), .S0 (n_179), .SI (\fifo[7] [9]), .SE (SE), .Q
       (\fifo[7] [10]));
  SMDFFHQX1 \fifo_reg[7][27] (.CK (clk), .D0 (\fifo[7] [27]), .D1
       (data_in[27]), .S0 (n_179), .SI (\fifo[7] [26]), .SE (SE), .Q
       (\fifo[7] [27]));
  SMDFFHQX1 \fifo_reg[3][30] (.CK (clk), .D0 (\fifo[3] [30]), .D1
       (data_in[30]), .S0 (n_178), .SI (\fifo[3] [29]), .SE (SE), .Q
       (\fifo[3] [30]));
  SMDFFHQX1 \fifo_reg[7][30] (.CK (clk), .D0 (\fifo[7] [30]), .D1
       (data_in[30]), .S0 (n_179), .SI (\fifo[7] [29]), .SE (SE), .Q
       (\fifo[7] [30]));
  SMDFFHQX1 \fifo_reg[7][26] (.CK (clk), .D0 (\fifo[7] [26]), .D1
       (data_in[26]), .S0 (n_179), .SI (\fifo[7] [25]), .SE (SE), .Q
       (\fifo[7] [26]));
  SMDFFHQX1 \fifo_reg[7][22] (.CK (clk), .D0 (\fifo[7] [22]), .D1
       (data_in[22]), .S0 (n_179), .SI (\fifo[7] [21]), .SE (SE), .Q
       (\fifo[7] [22]));
  SMDFFHQX1 \fifo_reg[7][18] (.CK (clk), .D0 (\fifo[7] [18]), .D1
       (data_in[18]), .S0 (n_179), .SI (\fifo[7] [17]), .SE (SE), .Q
       (\fifo[7] [18]));
  SMDFFHQX1 \fifo_reg[3][18] (.CK (clk), .D0 (\fifo[3] [18]), .D1
       (data_in[18]), .S0 (n_178), .SI (\fifo[3] [17]), .SE (SE), .Q
       (\fifo[3] [18]));
  SMDFFHQX1 \fifo_reg[3][2] (.CK (clk), .D0 (\fifo[3] [2]), .D1
       (data_in[2]), .S0 (n_178), .SI (\fifo[3] [1]), .SE (SE), .Q
       (\fifo[3] [2]));
  SMDFFHQX1 \fifo_reg[3][22] (.CK (clk), .D0 (\fifo[3] [22]), .D1
       (data_in[22]), .S0 (n_178), .SI (\fifo[3] [21]), .SE (SE), .Q
       (\fifo[3] [22]));
  SMDFFHQX1 \fifo_reg[3][6] (.CK (clk), .D0 (\fifo[3] [6]), .D1
       (data_in[6]), .S0 (n_178), .SI (\fifo[3] [5]), .SE (SE), .Q
       (\fifo[3] [6]));
  SMDFFHQX1 \fifo_reg[3][14] (.CK (clk), .D0 (\fifo[3] [14]), .D1
       (data_in[14]), .S0 (n_178), .SI (\fifo[3] [13]), .SE (SE), .Q
       (\fifo[3] [14]));
  SMDFFHQX1 \fifo_reg[3][10] (.CK (clk), .D0 (\fifo[3] [10]), .D1
       (data_in[10]), .S0 (n_178), .SI (\fifo[3] [9]), .SE (SE), .Q
       (\fifo[3] [10]));
  SMDFFHQX1 \fifo_reg[3][28] (.CK (clk), .D0 (\fifo[3] [28]), .D1
       (data_in[28]), .S0 (n_178), .SI (\fifo[3] [27]), .SE (SE), .Q
       (\fifo[3] [28]));
  SMDFFHQX1 \fifo_reg[3][29] (.CK (clk), .D0 (\fifo[3] [29]), .D1
       (data_in[29]), .S0 (n_178), .SI (\fifo[3] [28]), .SE (SE), .Q
       (\fifo[3] [29]));
  SMDFFHQX1 \fifo_reg[3][31] (.CK (clk), .D0 (\fifo[3] [31]), .D1
       (data_in[31]), .S0 (n_178), .SI (\fifo[3] [30]), .SE (SE), .Q
       (\fifo[3] [31]));
  SMDFFHQX1 \fifo_reg[7][0] (.CK (clk), .D0 (\fifo[7] [0]), .D1
       (data_in[0]), .S0 (n_179), .SI (\fifo[6] [31]), .SE (SE), .Q
       (\fifo[7] [0]));
  SMDFFHQX1 \fifo_reg[7][1] (.CK (clk), .D0 (\fifo[7] [1]), .D1
       (data_in[1]), .S0 (n_179), .SI (\fifo[7] [0]), .SE (SE), .Q
       (\fifo[7] [1]));
  SMDFFHQX1 \fifo_reg[7][3] (.CK (clk), .D0 (\fifo[7] [3]), .D1
       (data_in[3]), .S0 (n_179), .SI (\fifo[7] [2]), .SE (SE), .Q
       (\fifo[7] [3]));
  SMDFFHQX1 \fifo_reg[7][4] (.CK (clk), .D0 (\fifo[7] [4]), .D1
       (data_in[4]), .S0 (n_179), .SI (\fifo[7] [3]), .SE (SE), .Q
       (\fifo[7] [4]));
  SMDFFHQX1 \fifo_reg[7][5] (.CK (clk), .D0 (\fifo[7] [5]), .D1
       (data_in[5]), .S0 (n_179), .SI (\fifo[7] [4]), .SE (SE), .Q
       (\fifo[7] [5]));
  SMDFFHQX1 \fifo_reg[7][6] (.CK (clk), .D0 (\fifo[7] [6]), .D1
       (data_in[6]), .S0 (n_179), .SI (\fifo[7] [5]), .SE (SE), .Q
       (\fifo[7] [6]));
  SMDFFHQX1 \fifo_reg[7][7] (.CK (clk), .D0 (\fifo[7] [7]), .D1
       (data_in[7]), .S0 (n_179), .SI (\fifo[7] [6]), .SE (SE), .Q
       (\fifo[7] [7]));
  SMDFFHQX1 \fifo_reg[7][8] (.CK (clk), .D0 (\fifo[7] [8]), .D1
       (data_in[8]), .S0 (n_179), .SI (\fifo[7] [7]), .SE (SE), .Q
       (\fifo[7] [8]));
  SMDFFHQX1 \fifo_reg[7][9] (.CK (clk), .D0 (\fifo[7] [9]), .D1
       (data_in[9]), .S0 (n_179), .SI (\fifo[7] [8]), .SE (SE), .Q
       (\fifo[7] [9]));
  SMDFFHQX1 \fifo_reg[7][11] (.CK (clk), .D0 (\fifo[7] [11]), .D1
       (data_in[11]), .S0 (n_179), .SI (\fifo[7] [10]), .SE (SE), .Q
       (\fifo[7] [11]));
  SMDFFHQX1 \fifo_reg[7][12] (.CK (clk), .D0 (\fifo[7] [12]), .D1
       (data_in[12]), .S0 (n_179), .SI (\fifo[7] [11]), .SE (SE), .Q
       (\fifo[7] [12]));
  SMDFFHQX1 \fifo_reg[7][13] (.CK (clk), .D0 (\fifo[7] [13]), .D1
       (data_in[13]), .S0 (n_179), .SI (\fifo[7] [12]), .SE (SE), .Q
       (\fifo[7] [13]));
  SMDFFHQX1 \fifo_reg[7][15] (.CK (clk), .D0 (\fifo[7] [15]), .D1
       (data_in[15]), .S0 (n_179), .SI (\fifo[7] [14]), .SE (SE), .Q
       (\fifo[7] [15]));
  SMDFFHQX1 \fifo_reg[7][16] (.CK (clk), .D0 (\fifo[7] [16]), .D1
       (data_in[16]), .S0 (n_179), .SI (\fifo[7] [15]), .SE (SE), .Q
       (\fifo[7] [16]));
  NAND2XL g7694__8246(.A (n_112), .B (n_141), .Y (n_177));
  SMDFFHQX1 \fifo_reg[7][19] (.CK (clk), .D0 (\fifo[7] [19]), .D1
       (data_in[19]), .S0 (n_179), .SI (\fifo[7] [18]), .SE (SE), .Q
       (\fifo[7] [19]));
  SMDFFHQX1 \fifo_reg[7][20] (.CK (clk), .D0 (\fifo[7] [20]), .D1
       (data_in[20]), .S0 (n_179), .SI (\fifo[7] [19]), .SE (SE), .Q
       (\fifo[7] [20]));
  SMDFFHQX1 \fifo_reg[7][21] (.CK (clk), .D0 (\fifo[7] [21]), .D1
       (data_in[21]), .S0 (n_179), .SI (\fifo[7] [20]), .SE (SE), .Q
       (\fifo[7] [21]));
  SMDFFHQX1 \fifo_reg[7][23] (.CK (clk), .D0 (\fifo[7] [23]), .D1
       (data_in[23]), .S0 (n_179), .SI (\fifo[7] [22]), .SE (SE), .Q
       (\fifo[7] [23]));
  SMDFFHQX1 \fifo_reg[7][24] (.CK (clk), .D0 (\fifo[7] [24]), .D1
       (data_in[24]), .S0 (n_179), .SI (\fifo[7] [23]), .SE (SE), .Q
       (\fifo[7] [24]));
  SMDFFHQX1 \fifo_reg[7][25] (.CK (clk), .D0 (\fifo[7] [25]), .D1
       (data_in[25]), .S0 (n_179), .SI (\fifo[7] [24]), .SE (SE), .Q
       (\fifo[7] [25]));
  SMDFFHQX1 \fifo_reg[7][28] (.CK (clk), .D0 (\fifo[7] [28]), .D1
       (data_in[28]), .S0 (n_179), .SI (\fifo[7] [27]), .SE (SE), .Q
       (\fifo[7] [28]));
  SMDFFHQX1 \fifo_reg[7][29] (.CK (clk), .D0 (\fifo[7] [29]), .D1
       (data_in[29]), .S0 (n_179), .SI (\fifo[7] [28]), .SE (SE), .Q
       (\fifo[7] [29]));
  SMDFFHQX1 \fifo_reg[7][31] (.CK (clk), .D0 (\fifo[7] [31]), .D1
       (data_in[31]), .S0 (n_179), .SI (\fifo[7] [30]), .SE (SE), .Q
       (\fifo[7] [31]));
  SMDFFHQX1 \fifo_reg[7][17] (.CK (clk), .D0 (\fifo[7] [17]), .D1
       (data_in[17]), .S0 (n_179), .SI (\fifo[7] [16]), .SE (SE), .Q
       (\fifo[7] [17]));
  SMDFFHQX1 \fifo_reg[7][14] (.CK (clk), .D0 (\fifo[7] [14]), .D1
       (data_in[14]), .S0 (n_179), .SI (\fifo[7] [13]), .SE (SE), .Q
       (\fifo[7] [14]));
  SMDFFHQX1 \fifo_reg[3][0] (.CK (clk), .D0 (\fifo[3] [0]), .D1
       (data_in[0]), .S0 (n_178), .SI (\fifo[2] [31]), .SE (SE), .Q
       (\fifo[3] [0]));
  SMDFFHQX1 \fifo_reg[3][1] (.CK (clk), .D0 (\fifo[3] [1]), .D1
       (data_in[1]), .S0 (n_178), .SI (\fifo[3] [0]), .SE (SE), .Q
       (\fifo[3] [1]));
  SMDFFHQX1 \fifo_reg[3][3] (.CK (clk), .D0 (\fifo[3] [3]), .D1
       (data_in[3]), .S0 (n_178), .SI (\fifo[3] [2]), .SE (SE), .Q
       (\fifo[3] [3]));
  SMDFFHQX1 \fifo_reg[3][4] (.CK (clk), .D0 (\fifo[3] [4]), .D1
       (data_in[4]), .S0 (n_178), .SI (\fifo[3] [3]), .SE (SE), .Q
       (\fifo[3] [4]));
  SMDFFHQX1 \fifo_reg[3][5] (.CK (clk), .D0 (\fifo[3] [5]), .D1
       (data_in[5]), .S0 (n_178), .SI (\fifo[3] [4]), .SE (SE), .Q
       (\fifo[3] [5]));
  SMDFFHQX1 \fifo_reg[3][7] (.CK (clk), .D0 (\fifo[3] [7]), .D1
       (data_in[7]), .S0 (n_178), .SI (\fifo[3] [6]), .SE (SE), .Q
       (\fifo[3] [7]));
  SMDFFHQX1 \fifo_reg[3][8] (.CK (clk), .D0 (\fifo[3] [8]), .D1
       (data_in[8]), .S0 (n_178), .SI (\fifo[3] [7]), .SE (SE), .Q
       (\fifo[3] [8]));
  SMDFFHQX1 \fifo_reg[3][9] (.CK (clk), .D0 (\fifo[3] [9]), .D1
       (data_in[9]), .S0 (n_178), .SI (\fifo[3] [8]), .SE (SE), .Q
       (\fifo[3] [9]));
  SMDFFHQX1 \fifo_reg[3][11] (.CK (clk), .D0 (\fifo[3] [11]), .D1
       (data_in[11]), .S0 (n_178), .SI (\fifo[3] [10]), .SE (SE), .Q
       (\fifo[3] [11]));
  SMDFFHQX1 \fifo_reg[3][12] (.CK (clk), .D0 (\fifo[3] [12]), .D1
       (data_in[12]), .S0 (n_178), .SI (\fifo[3] [11]), .SE (SE), .Q
       (\fifo[3] [12]));
  SMDFFHQX1 \fifo_reg[3][13] (.CK (clk), .D0 (\fifo[3] [13]), .D1
       (data_in[13]), .S0 (n_178), .SI (\fifo[3] [12]), .SE (SE), .Q
       (\fifo[3] [13]));
  SMDFFHQX1 \fifo_reg[3][15] (.CK (clk), .D0 (\fifo[3] [15]), .D1
       (data_in[15]), .S0 (n_178), .SI (\fifo[3] [14]), .SE (SE), .Q
       (\fifo[3] [15]));
  SMDFFHQX1 \fifo_reg[3][16] (.CK (clk), .D0 (\fifo[3] [16]), .D1
       (data_in[16]), .S0 (n_178), .SI (\fifo[3] [15]), .SE (SE), .Q
       (\fifo[3] [16]));
  SMDFFHQX1 \fifo_reg[3][17] (.CK (clk), .D0 (\fifo[3] [17]), .D1
       (data_in[17]), .S0 (n_178), .SI (\fifo[3] [16]), .SE (SE), .Q
       (\fifo[3] [17]));
  SMDFFHQX1 \fifo_reg[3][19] (.CK (clk), .D0 (\fifo[3] [19]), .D1
       (data_in[19]), .S0 (n_178), .SI (\fifo[3] [18]), .SE (SE), .Q
       (\fifo[3] [19]));
  SMDFFHQX1 \fifo_reg[3][20] (.CK (clk), .D0 (\fifo[3] [20]), .D1
       (data_in[20]), .S0 (n_178), .SI (\fifo[3] [19]), .SE (SE), .Q
       (\fifo[3] [20]));
  SMDFFHQX1 \fifo_reg[3][21] (.CK (clk), .D0 (\fifo[3] [21]), .D1
       (data_in[21]), .S0 (n_178), .SI (\fifo[3] [20]), .SE (SE), .Q
       (\fifo[3] [21]));
  SMDFFHQX1 \fifo_reg[3][23] (.CK (clk), .D0 (\fifo[3] [23]), .D1
       (data_in[23]), .S0 (n_178), .SI (\fifo[3] [22]), .SE (SE), .Q
       (\fifo[3] [23]));
  SMDFFHQX1 \fifo_reg[3][24] (.CK (clk), .D0 (\fifo[3] [24]), .D1
       (data_in[24]), .S0 (n_178), .SI (\fifo[3] [23]), .SE (SE), .Q
       (\fifo[3] [24]));
  SMDFFHQX1 \fifo_reg[3][25] (.CK (clk), .D0 (\fifo[3] [25]), .D1
       (data_in[25]), .S0 (n_178), .SI (\fifo[3] [24]), .SE (SE), .Q
       (\fifo[3] [25]));
  SMDFFHQX1 \fifo_reg[3][26] (.CK (clk), .D0 (\fifo[3] [26]), .D1
       (data_in[26]), .S0 (n_178), .SI (\fifo[3] [25]), .SE (SE), .Q
       (\fifo[3] [26]));
  SMDFFHQX1 \fifo_reg[3][27] (.CK (clk), .D0 (\fifo[3] [27]), .D1
       (data_in[27]), .S0 (n_178), .SI (\fifo[3] [26]), .SE (SE), .Q
       (\fifo[3] [27]));
  AOI222XL g7894__7098(.A0 (n_252), .A1 (\fifo[3] [22]), .B0 (n_245),
       .B1 (\fifo[1] [22]), .C0 (\fifo[6] [22]), .C1 (n_174), .Y
       (n_176));
  AOI222XL g7881__6131(.A0 (n_171), .A1 (data_out[14]), .B0 (n_170),
       .B1 (\fifo[0] [14]), .C0 (\fifo[6] [14]), .C1 (n_174), .Y
       (n_175));
  AOI222XL g7882__1881(.A0 (n_252), .A1 (\fifo[3] [15]), .B0 (n_245),
       .B1 (\fifo[1] [15]), .C0 (\fifo[6] [15]), .C1 (n_174), .Y
       (n_173));
  AOI222XL g7883__5115(.A0 (n_171), .A1 (data_out[5]), .B0 (n_170), .B1
       (\fifo[0] [5]), .C0 (\fifo[4] [5]), .C1 (n_242), .Y (n_172));
  AOI222XL g7884__7482(.A0 (n_170), .A1 (\fifo[0] [16]), .B0 (n_245),
       .B1 (\fifo[1] [16]), .C0 (\fifo[3] [16]), .C1 (n_252), .Y
       (n_169));
  AOI222XL g7885__4733(.A0 (n_240), .A1 (\fifo[2] [0]), .B0 (n_242),
       .B1 (\fifo[4] [0]), .C0 (\fifo[6] [0]), .C1 (n_174), .Y (n_168));
  AOI222XL g7886__6161(.A0 (n_170), .A1 (\fifo[0] [17]), .B0 (n_245),
       .B1 (\fifo[1] [17]), .C0 (\fifo[3] [17]), .C1 (n_252), .Y
       (n_167));
  AOI222XL g7887__9315(.A0 (n_171), .A1 (data_out[18]), .B0 (n_245),
       .B1 (\fifo[1] [18]), .C0 (\fifo[6] [18]), .C1 (n_174), .Y
       (n_166));
  AOI222XL g7888__9945(.A0 (n_170), .A1 (\fifo[0] [6]), .B0 (n_240),
       .B1 (\fifo[2] [6]), .C0 (\fifo[6] [6]), .C1 (n_174), .Y (n_165));
  AOI222XL g7889__2883(.A0 (n_170), .A1 (\fifo[0] [19]), .B0 (n_240),
       .B1 (\fifo[2] [19]), .C0 (\fifo[6] [19]), .C1 (n_174), .Y
       (n_164));
  AOI222XL g7890__2346(.A0 (n_170), .A1 (\fifo[0] [7]), .B0 (n_251),
       .B1 (\fifo[5] [7]), .C0 (\fifo[3] [7]), .C1 (n_252), .Y (n_163));
  AOI222XL g7891__1666(.A0 (n_252), .A1 (\fifo[3] [20]), .B0 (n_170),
       .B1 (\fifo[0] [20]), .C0 (\fifo[6] [20]), .C1 (n_174), .Y
       (n_162));
  AOI222XL g7892__7410(.A0 (n_171), .A1 (data_out[21]), .B0 (n_170),
       .B1 (\fifo[0] [21]), .C0 (\fifo[2] [21]), .C1 (n_240), .Y
       (n_161));
  AOI222XL g7879__6417(.A0 (n_171), .A1 (data_out[25]), .B0 (n_170),
       .B1 (\fifo[0] [25]), .C0 (\fifo[1] [25]), .C1 (n_245), .Y
       (n_160));
  AOI222XL g7905__5477(.A0 (n_170), .A1 (\fifo[0] [28]), .B0 (n_242),
       .B1 (\fifo[4] [28]), .C0 (\fifo[6] [28]), .C1 (n_174), .Y
       (n_159));
  AOI222XL g7897__2398(.A0 (n_170), .A1 (\fifo[0] [9]), .B0 (n_240),
       .B1 (\fifo[2] [9]), .C0 (\fifo[6] [9]), .C1 (n_174), .Y (n_158));
  AOI222XL g7898__5107(.A0 (n_171), .A1 (data_out[24]), .B0 (n_170),
       .B1 (\fifo[0] [24]), .C0 (\fifo[4] [24]), .C1 (n_242), .Y
       (n_157));
  AOI222XL g7900__6260(.A0 (n_170), .A1 (\fifo[0] [2]), .B0 (n_245),
       .B1 (\fifo[1] [2]), .C0 (\fifo[3] [2]), .C1 (n_252), .Y (n_156));
  AOI222XL g7901__4319(.A0 (n_170), .A1 (\fifo[0] [10]), .B0 (n_240),
       .B1 (\fifo[2] [10]), .C0 (\fifo[6] [10]), .C1 (n_174), .Y
       (n_155));
  AOI222XL g7903__8428(.A0 (n_171), .A1 (data_out[27]), .B0 (n_170),
       .B1 (\fifo[0] [27]), .C0 (\fifo[4] [27]), .C1 (n_242), .Y
       (n_154));
  AOI222XL g7904__5526(.A0 (n_247), .A1 (\fifo[7] [11]), .B0 (n_170),
       .B1 (\fifo[0] [11]), .C0 (\fifo[6] [11]), .C1 (n_174), .Y
       (n_153));
  AOI222XL g7896__6783(.A0 (n_171), .A1 (data_out[23]), .B0 (n_170),
       .B1 (\fifo[0] [23]), .C0 (\fifo[5] [23]), .C1 (n_251), .Y
       (n_152));
  AOI222XL g7906__3680(.A0 (n_245), .A1 (\fifo[1] [29]), .B0 (n_252),
       .B1 (\fifo[3] [29]), .C0 (\fifo[6] [29]), .C1 (n_174), .Y
       (n_151));
  AOI222XL g7907__1617(.A0 (n_252), .A1 (\fifo[3] [3]), .B0 (n_245),
       .B1 (\fifo[1] [3]), .C0 (\fifo[6] [3]), .C1 (n_174), .Y (n_150));
  AOI222XL g7908__2802(.A0 (n_171), .A1 (data_out[30]), .B0 (n_245),
       .B1 (\fifo[1] [30]), .C0 (\fifo[6] [30]), .C1 (n_174), .Y
       (n_149));
  AOI222XL g7909__1705(.A0 (n_171), .A1 (data_out[12]), .B0 (n_170),
       .B1 (\fifo[0] [12]), .C0 (\fifo[3] [12]), .C1 (n_252), .Y
       (n_148));
  AOI222XL g7910__5122(.A0 (n_171), .A1 (data_out[31]), .B0 (n_245),
       .B1 (\fifo[1] [31]), .C0 (\fifo[6] [31]), .C1 (n_174), .Y
       (n_147));
  AOI222XL g7911__8246(.A0 (n_170), .A1 (\fifo[0] [13]), .B0 (n_251),
       .B1 (\fifo[5] [13]), .C0 (\fifo[3] [13]), .C1 (n_252), .Y
       (n_146));
  AOI222XL g7912__7098(.A0 (\fifo[2] [4]), .A1 (n_240), .B0 (n_242),
       .B1 (\fifo[4] [4]), .C0 (n_170), .C1 (\fifo[0] [4]), .Y (n_145));
  AOI22XL g8077__6131(.A0 (\fifo[4] [29]), .A1 (n_242), .B0
       (\fifo[5] [29]), .B1 (n_251), .Y (n_144));
  AOI22X1 g8076__1881(.A0 (n_171), .A1 (data_out[28]), .B0 (n_240), .B1
       (\fifo[2] [28]), .Y (n_143));
  AOI222XL g7893__5115(.A0 (n_251), .A1 (\fifo[5] [8]), .B0 (n_174),
       .B1 (\fifo[6] [8]), .C0 (\fifo[7] [8]), .C1 (n_247), .Y (n_142));
  AOI222XL g7895__7482(.A0 (n_252), .A1 (\fifo[3] [1]), .B0 (n_251),
       .B1 (\fifo[5] [1]), .C0 (\fifo[6] [1]), .C1 (n_174), .Y (n_141));
  AOI222XL g7902__4733(.A0 (n_171), .A1 (data_out[26]), .B0 (n_251),
       .B1 (\fifo[5] [26]), .C0 (\fifo[6] [26]), .C1 (n_174), .Y
       (n_140));
  AOI22XL g8079__6161(.A0 (data_out[29]), .A1 (n_171), .B0
       (\fifo[0] [29]), .B1 (n_170), .Y (n_139));
  OAI211X1 g8091__9315(.A0 (write_pointer[2]), .A1 (n_60), .B0 (n_134),
       .C0 (n_43), .Y (n_138));
  AOI22XL g8084__9945(.A0 (\fifo[4] [31]), .A1 (n_242), .B0
       (\fifo[5] [31]), .B1 (n_251), .Y (n_137));
  MXI2XL g7913__2883(.A (n_135), .B (n_134), .S0 (write_pointer[0]), .Y
       (n_136));
  AOI22XL g8027__2346(.A0 (data_out[19]), .A1 (n_171), .B0
       (\fifo[4] [19]), .B1 (n_242), .Y (n_133));
  AOI22XL g8030__1666(.A0 (data_out[15]), .A1 (n_171), .B0
       (\fifo[0] [15]), .B1 (n_170), .Y (n_132));
  AOI22XL g8031__7410(.A0 (\fifo[4] [16]), .A1 (n_242), .B0
       (\fifo[7] [16]), .B1 (n_247), .Y (n_131));
  AOI22XL g8032__6417(.A0 (\fifo[2] [5]), .A1 (n_240), .B0 (\fifo[6]
       [5]), .B1 (n_174), .Y (n_130));
  AOI22XL g8033__5477(.A0 (data_out[0]), .A1 (n_171), .B0 (\fifo[0]
       [0]), .B1 (n_170), .Y (n_129));
  AOI22XL g8035__2398(.A0 (\fifo[1] [6]), .A1 (n_245), .B0 (\fifo[5]
       [6]), .B1 (n_251), .Y (n_128));
  AOI22XL g8036__5107(.A0 (\fifo[4] [17]), .A1 (n_242), .B0
       (\fifo[5] [17]), .B1 (n_251), .Y (n_127));
  AOI22XL g8038__6260(.A0 (\fifo[2] [18]), .A1 (n_240), .B0
       (\fifo[5] [18]), .B1 (n_251), .Y (n_126));
  AOI22XL g8039__4319(.A0 (data_out[6]), .A1 (n_171), .B0 (\fifo[4]
       [6]), .B1 (n_242), .Y (n_125));
  AOI22XL g8040__8428(.A0 (\fifo[0] [18]), .A1 (n_170), .B0
       (\fifo[3] [18]), .B1 (n_252), .Y (n_124));
  AOI22XL g8041__5526(.A0 (\fifo[1] [19]), .A1 (n_245), .B0
       (\fifo[5] [19]), .B1 (n_251), .Y (n_123));
  AOI22XL g8042__6783(.A0 (\fifo[4] [7]), .A1 (n_242), .B0 (\fifo[7]
       [7]), .B1 (n_247), .Y (n_122));
  AOI22XL g8043__3680(.A0 (\fifo[2] [15]), .A1 (n_240), .B0
       (\fifo[7] [15]), .B1 (n_247), .Y (n_121));
  AOI22XL g8074__1617(.A0 (\fifo[1] [28]), .A1 (n_245), .B0
       (\fifo[5] [28]), .B1 (n_251), .Y (n_120));
  AOI22XL g8044__2802(.A0 (\fifo[1] [1]), .A1 (n_245), .B0 (\fifo[4]
       [1]), .B1 (n_242), .Y (n_119));
  AOI22XL g8045__1705(.A0 (\fifo[1] [20]), .A1 (n_245), .B0
       (\fifo[2] [20]), .B1 (n_240), .Y (n_118));
  AOI22XL g8047__5122(.A0 (data_out[20]), .A1 (n_171), .B0
       (\fifo[4] [20]), .B1 (n_242), .Y (n_117));
  AOI22X1 g8048__8246(.A0 (n_242), .A1 (\fifo[4] [14]), .B0 (n_252),
       .B1 (\fifo[3] [14]), .Y (n_116));
  AOI22XL g8082__7098(.A0 (\fifo[1] [12]), .A1 (n_245), .B0
       (\fifo[6] [12]), .B1 (n_174), .Y (n_115));
  AOI22XL g8090__6131(.A0 (\fifo[2] [14]), .A1 (n_240), .B0
       (\fifo[5] [14]), .B1 (n_251), .Y (n_114));
  AOI22XL g8080__1881(.A0 (data_out[3]), .A1 (n_171), .B0 (\fifo[0]
       [3]), .B1 (n_170), .Y (n_113));
  AOI22XL g8051__5115(.A0 (data_out[1]), .A1 (n_171), .B0 (\fifo[0]
       [1]), .B1 (n_170), .Y (n_112));
  AOI22XL g8052__7482(.A0 (\fifo[4] [21]), .A1 (n_242), .B0
       (\fifo[6] [21]), .B1 (n_174), .Y (n_111));
  AOI22XL g8053__4733(.A0 (data_out[8]), .A1 (n_171), .B0 (\fifo[0]
       [8]), .B1 (n_170), .Y (n_110));
  AOI22XL g8054__6161(.A0 (\fifo[4] [22]), .A1 (n_242), .B0
       (\fifo[5] [22]), .B1 (n_251), .Y (n_109));
  AOI22XL g8055__9315(.A0 (data_out[22]), .A1 (n_171), .B0
       (\fifo[0] [22]), .B1 (n_170), .Y (n_108));
  AOI22XL g8056__9945(.A0 (\fifo[1] [23]), .A1 (n_245), .B0
       (\fifo[2] [23]), .B1 (n_240), .Y (n_107));
  AOI22XL g8057__2883(.A0 (\fifo[1] [9]), .A1 (n_245), .B0 (\fifo[5]
       [9]), .B1 (n_251), .Y (n_106));
  AOI22XL g8059__2346(.A0 (data_out[11]), .A1 (n_171), .B0
       (\fifo[4] [11]), .B1 (n_242), .Y (n_105));
  AOI22XL g8060__1666(.A0 (\fifo[1] [24]), .A1 (n_245), .B0
       (\fifo[7] [24]), .B1 (n_247), .Y (n_104));
  AOI22XL g8061__7410(.A0 (data_out[9]), .A1 (n_171), .B0 (\fifo[4]
       [9]), .B1 (n_242), .Y (n_103));
  AOI22XL g8062__6417(.A0 (\fifo[2] [24]), .A1 (n_240), .B0
       (\fifo[6] [24]), .B1 (n_174), .Y (n_102));
  AOI22XL g8063__5477(.A0 (\fifo[2] [25]), .A1 (n_240), .B0
       (\fifo[7] [25]), .B1 (n_247), .Y (n_101));
  AOI22XL g8064__2398(.A0 (\fifo[1] [10]), .A1 (n_245), .B0
       (\fifo[7] [10]), .B1 (n_247), .Y (n_100));
  AOI22XL g8067__5107(.A0 (\fifo[4] [26]), .A1 (n_242), .B0
       (\fifo[7] [26]), .B1 (n_247), .Y (n_99));
  AOI22XL g8068__6260(.A0 (data_out[10]), .A1 (n_171), .B0
       (\fifo[4] [10]), .B1 (n_242), .Y (n_98));
  AOI22XL g8069__4319(.A0 (\fifo[0] [26]), .A1 (n_170), .B0
       (\fifo[3] [26]), .B1 (n_252), .Y (n_97));
  AOI22XL g8071__8428(.A0 (\fifo[1] [11]), .A1 (n_245), .B0
       (\fifo[2] [11]), .B1 (n_240), .Y (n_96));
  AOI22XL g8072__5526(.A0 (\fifo[2] [3]), .A1 (n_240), .B0 (\fifo[7]
       [3]), .B1 (n_247), .Y (n_95));
  AOI22XL g8073__6783(.A0 (\fifo[2] [27]), .A1 (n_240), .B0
       (\fifo[6] [27]), .B1 (n_174), .Y (n_94));
  AOI22XL g8075__3680(.A0 (\fifo[2] [2]), .A1 (n_240), .B0 (\fifo[7]
       [2]), .B1 (n_247), .Y (n_93));
  AOI22XL g8086__1617(.A0 (\fifo[0] [31]), .A1 (n_170), .B0
       (\fifo[3] [31]), .B1 (n_252), .Y (n_92));
  AOI22XL g8078__2802(.A0 (\fifo[4] [12]), .A1 (n_242), .B0
       (\fifo[5] [12]), .B1 (n_251), .Y (n_91));
  AOI22XL g8081__1705(.A0 (\fifo[4] [30]), .A1 (n_242), .B0
       (\fifo[7] [30]), .B1 (n_247), .Y (n_90));
  AOI22XL g8083__5122(.A0 (\fifo[0] [30]), .A1 (n_170), .B0
       (\fifo[3] [30]), .B1 (n_252), .Y (n_89));
  AOI22XL g8085__8246(.A0 (\fifo[1] [13]), .A1 (n_245), .B0
       (\fifo[4] [13]), .B1 (n_242), .Y (n_88));
  AOI22XL g8050__7098(.A0 (\fifo[2] [8]), .A1 (n_240), .B0 (\fifo[3]
       [8]), .B1 (n_252), .Y (n_87));
  AOI22XL g8089__6131(.A0 (data_out[4]), .A1 (n_171), .B0 (\fifo[6]
       [4]), .B1 (n_174), .Y (n_86));
  AOI22X1 g8070__1881(.A0 (n_252), .A1 (\fifo[3] [27]), .B0 (n_247),
       .B1 (\fifo[7] [27]), .Y (n_85));
  MX2X1 g7914__5115(.A (n_44), .B (write_pointer[3]), .S0 (n_135), .Y
       (n_84));
  MXI2XL g7915__7482(.A (read_pointer[0]), .B (n_8), .S0 (n_81), .Y
       (n_83));
  MX3X1 g7916__4733(.A (read_pointer[3]), .B (n_1), .C
       (read_pointer[3]), .S0 (n_26), .S1 (n_81), .Y (n_82));
  MXI2XL g7917__6161(.A (n_5), .B (n_21), .S0 (n_81), .Y (n_80));
  MX2X1 g7918__9315(.A (n_35), .B (read_pointer[2]), .S0 (n_81), .Y
       (n_79));
  AOI22XL g8087__9945(.A0 (\fifo[5] [4]), .A1 (n_251), .B0 (\fifo[3]
       [4]), .B1 (n_252), .Y (n_78));
  MX2X1 g7880__2883(.A (n_14), .B (write_pointer[1]), .S0 (n_135), .Y
       (n_77));
  AOI22XL g8028__2346(.A0 (\fifo[5] [5]), .A1 (n_251), .B0 (\fifo[3]
       [5]), .B1 (n_252), .Y (n_76));
  AOI22XL g8029__1666(.A0 (\fifo[5] [0]), .A1 (n_251), .B0 (\fifo[3]
       [0]), .B1 (n_252), .Y (n_75));
  AOI22XL g8034__7410(.A0 (data_out[16]), .A1 (n_171), .B0
       (\fifo[6] [16]), .B1 (n_174), .Y (n_74));
  AOI22XL g8037__6417(.A0 (data_out[17]), .A1 (n_171), .B0
       (\fifo[6] [17]), .B1 (n_174), .Y (n_73));
  AOI22XL g8046__5477(.A0 (data_out[7]), .A1 (n_171), .B0 (\fifo[6]
       [7]), .B1 (n_174), .Y (n_72));
  AOI22XL g8049__2398(.A0 (\fifo[5] [21]), .A1 (n_251), .B0
       (\fifo[3] [21]), .B1 (n_252), .Y (n_71));
  AOI22XL g8058__5107(.A0 (\fifo[6] [23]), .A1 (n_174), .B0
       (\fifo[7] [23]), .B1 (n_247), .Y (n_70));
  AOI22XL g8065__6260(.A0 (data_out[2]), .A1 (n_171), .B0 (\fifo[6]
       [2]), .B1 (n_174), .Y (n_69));
  AOI22XL g8066__4319(.A0 (\fifo[3] [25]), .A1 (n_252), .B0
       (\fifo[6] [25]), .B1 (n_174), .Y (n_68));
  AOI22XL g8088__8428(.A0 (data_out[13]), .A1 (n_171), .B0
       (\fifo[6] [13]), .B1 (n_174), .Y (n_67));
  AND3X1 g8105__5526(.A (n_66), .B (n_13), .C (n_41), .Y (n_245));
  OAI2BB1X2 g8102__6783(.A0N (n_65), .A1N (n_22), .B0 (n_62), .Y
       (n_198));
  OR2X2 g8100__3680(.A (n_56), .B (n_61), .Y (n_195));
  AND3X1 g8110__1617(.A (n_66), .B (n_15), .C (n_309), .Y (n_242));
  OAI2BB1X2 g8111__2802(.A0N (n_65), .A1N (n_20), .B0 (n_40), .Y
       (n_194));
  CLKINVX1 g8093(.A (n_135), .Y (n_134));
  AOI21X4 g8112__1705(.A0 (n_63), .A1 (n_25), .B0 (n_47), .Y (n_197));
  AND3X1 g8095__5122(.A (n_51), .B (n_64), .C (n_311), .Y (n_240));
  AND3X1 g8097__8246(.A (n_66), .B (n_64), .C (n_37), .Y (n_170));
  OAI2BB1X2 g8098__7098(.A0N (n_63), .A1N (n_23), .B0 (n_62), .Y
       (n_196));
  OR2X2 g8099__6131(.A (n_54), .B (n_61), .Y (n_193));
  NOR2X1 g8106__1881(.A (n_48), .B (n_57), .Y (n_251));
  OA21X2 g8103__5115(.A0 (n_55), .A1 (n_33), .B0 (n_60), .Y (n_178));
  OA21X2 g8101__7482(.A0 (n_53), .A1 (n_28), .B0 (n_60), .Y (n_179));
  NOR2X1 g8107__4733(.A (n_46), .B (n_19), .Y (n_252));
  NAND3BX1 g8092__6161(.AN (empty), .B (rd_en), .C (cs), .Y (n_81));
  NAND3BX1 g8094__9315(.AN (full), .B (wr_en), .C (cs), .Y (n_135));
  NOR2X1 g8108__9945(.A (n_50), .B (n_34), .Y (n_174));
  OR2X1 g8096__2883(.A (n_12), .B (empty), .Y (n_171));
  NOR2X1 g8109__2346(.A (n_52), .B (n_57), .Y (n_247));
  AOI21XL g8113__1666(.A0 (n_32), .A1 (n_2), .B0 (n_55), .Y (n_56));
  AOI21XL g8115__7410(.A0 (n_27), .A1 (n_16), .B0 (n_53), .Y (n_54));
  OAI21X1 g8116__6417(.A0 (n_45), .A1 (n_49), .B0 (n_51), .Y (n_52));
  OAI21X1 g8117__5477(.A0 (n_61), .A1 (n_49), .B0 (n_51), .Y (n_50));
  OAI21X1 g8118__2398(.A0 (n_47), .A1 (n_49), .B0 (n_66), .Y (n_48));
  OAI21X1 g8119__5107(.A0 (n_45), .A1 (n_29), .B0 (n_51), .Y (n_46));
  OAI21XL g8104__6260(.A0 (n_43), .A1 (write_pointer[3]), .B0 (n_24),
       .Y (n_44));
  NOR2XL g8120__4319(.A (n_17), .B (n_42), .Y (full));
  NAND2XL g8136__5526(.A (n_40), .B (n_38), .Y (n_41));
  NAND2XL g8125__3680(.A (n_62), .B (n_38), .Y (n_37));
  OAI211XL g8131__2802(.A0 (read_pointer[1]), .A1 (n_6), .B0 (n_34),
       .C0 (n_31), .Y (n_35));
  CLKINVX1 g8122(.A (n_53), .Y (n_63));
  INVXL g8123(.A (n_55), .Y (n_65));
  AND2XL g8126__1705(.A (n_32), .B (n_31), .Y (n_33));
  NOR2XL g8129__5122(.A (n_30), .B (n_49), .Y (n_53));
  NOR2XL g8130__8246(.A (n_30), .B (n_29), .Y (n_55));
  NOR2BXL g8127__7098(.AN (n_27), .B (n_26), .Y (n_28));
  OAI21X1 g8124__6131(.A0 (read_pointer[1]), .A1 (n_57), .B0 (n_27), .Y
       (n_25));
  NAND2XL g8114__1881(.A (write_pointer[3]), .B (n_43), .Y (n_24));
  OAI21XL g8133__5115(.A0 (read_pointer[1]), .A1 (n_34), .B0 (n_27), .Y
       (n_23));
  OAI2BB1XL g8135__7482(.A0N (n_21), .A1N (n_64), .B0 (n_32), .Y
       (n_22));
  OAI21XL g8134__4733(.A0 (read_pointer[1]), .A1 (n_19), .B0 (n_32), .Y
       (n_20));
  NAND3X1 g8137__6161(.A (n_7), .B (n_9), .C (n_4), .Y (n_42));
  CLKINVX1 g8141(.A (n_29), .Y (n_38));
  NAND2XL g8144__9315(.A (n_11), .B (n_17), .Y (n_29));
  NAND2XL g8145__9945(.A (write_pointer[2]), .B (n_17), .Y (n_49));
  NAND2XL g8146__2883(.A (read_pointer[1]), .B (n_15), .Y (n_16));
  NAND2XL g8147__2346(.A (n_61), .B (n_47), .Y (n_14));
  NAND2XL g8149__1666(.A (read_pointer[1]), .B (n_13), .Y (n_31));
  NOR2XL g8139__7410(.A (n_12), .B (read_pointer[1]), .Y (n_66));
  NOR2XL g8140__6417(.A (n_30), .B (n_11), .Y (n_27));
  NOR2XL g8143__5477(.A (n_30), .B (write_pointer[2]), .Y (n_32));
  NAND2XL g8150__2398(.A (write_pointer[2]), .B (n_60), .Y (n_43));
  NOR2XL g8138__5107(.A (n_12), .B (n_21), .Y (n_51));
  MXI2XL g8154__6260(.A (read_pointer[0]), .B (n_8), .S0
       (write_pointer[0]), .Y (n_9));
  AOI22X1 g8153__4319(.A0 (read_pointer[2]), .A1 (n_11), .B0
       (write_pointer[2]), .B1 (n_6), .Y (n_7));
  MXI2XL g8156__8428(.A (read_pointer[1]), .B (n_21), .S0
       (read_pointer[0]), .Y (n_5));
  MXI2XL g8155__5526(.A (read_pointer[1]), .B (n_21), .S0
       (write_pointer[1]), .Y (n_4));
  NOR2XL g8151__6783(.A (n_21), .B (n_57), .Y (n_26));
  NAND2XL g8148__3680(.A (read_pointer[1]), .B (n_64), .Y (n_2));
  CLKINVX1 g8168(.A (n_34), .Y (n_15));
  CLKINVX1 g8165(.A (n_19), .Y (n_13));
  CLKINVX1 g8166(.A (n_40), .Y (n_47));
  MXI2XL g8159__1617(.A (read_pointer[3]), .B (n_1), .S0
       (write_pointer[3]), .Y (n_17));
  NAND2XL g8169__2802(.A (read_pointer[0]), .B (n_6), .Y (n_19));
  NAND3XL g8157__1705(.A (rd_en), .B (rst_n), .C (cs), .Y (n_12));
  NAND3XL g8158__5122(.A (wr_en), .B (rst_n), .C (cs), .Y (n_30));
  NOR2XL g8170__8246(.A (write_pointer[1]), .B (n_0), .Y (n_40));
  NAND2XL g8172__7098(.A (read_pointer[2]), .B (n_8), .Y (n_34));
  CLKINVX1 g8160(.A (n_45), .Y (n_60));
  NAND2XL g8171__6131(.A (write_pointer[1]), .B (n_0), .Y (n_61));
  NOR2XL g8163__1881(.A (read_pointer[0]), .B (read_pointer[2]), .Y
       (n_64));
  NOR2XL g8161__5115(.A (write_pointer[0]), .B (write_pointer[1]), .Y
       (n_62));
  NAND2XL g8164__7482(.A (write_pointer[0]), .B (write_pointer[1]), .Y
       (n_45));
  NAND2XL g8162__4733(.A (read_pointer[0]), .B (read_pointer[2]), .Y
       (n_57));
  CLKINVX1 g8173(.A (read_pointer[3]), .Y (n_1));
  CLKINVX1 g8177(.A (write_pointer[2]), .Y (n_11));
  CLKINVX1 g8176(.A (read_pointer[2]), .Y (n_6));
  CLKINVX1 g8174(.A (write_pointer[0]), .Y (n_0));
  CLKINVX1 g8178(.A (read_pointer[0]), .Y (n_8));
  CLKINVX1 g8175(.A (read_pointer[1]), .Y (n_21));
  NAND2BX1 g2(.AN (n_49), .B (n_62), .Y (n_309));
  NOR2BX1 g8487(.AN (n_17), .B (n_42), .Y (empty));
  NAND2BX1 g8488(.AN (n_61), .B (n_38), .Y (n_311));
  BUFX20 rm_assigns_buf_scan_out(.A (write_pointer[3]), .Y (scan_out));
endmodule

